import {
  A2_TILE_LOOPS,
  NoA2Marking,
  OnlineA2Marking,
  a2Add,
  a2Key,
  a2Transform,
  makeHexBoundary,
  selectA2FrozenMarking,
  solveA2Tiling,
  tileOrientations
} from "../../assets/a2-tiling-engine.js?v=20260721-frontier-memo";

const $ = id => document.getElementById(id);
const canvas = $("canvas");
const ctx = canvas.getContext("2d");
const builderCanvas = $("tileBuilderCanvas");
const builderCtx = builderCanvas.getContext("2d");
const sqrt3 = Math.sqrt(3);
const palette = ["#e59a3a", "#247f89", "#a66bb1", "#d65f5f", "#5579bd", "#7a9848", "#c37a4a"];
// Outer boundary of a verified 101-Turtle patch generated by the shared tiler
// with the article's fixed marking. Its doubled A2 area is 4040 = 101 * 40.
const CERTIFIED_TURTLE_BOUNDARY = [[-20,14,6],[-21,14,7],[-20,12,8],[-21,11,10],[-22,10,12],[-21,8,13],[-22,8,14],[-22,7,15],[-20,6,14],[-19,4,15],[-18,2,16],[-16,1,15],[-16,0,16],[-17,0,17],[-16,-2,18],[-17,-3,20],[-16,-4,20],[-16,-5,21],[-14,-6,20],[-13,-8,21],[-14,-8,22],[-14,-9,23],[-12,-10,22],[-11,-12,23],[-10,-14,24],[-8,-15,23],[-8,-16,24],[-7,-17,24],[-8,-18,26],[-7,-20,27],[-8,-20,28],[-8,-21,29],[-6,-22,28],[-5,-21,26],[-4,-22,26],[-3,-22,25],[-2,-24,26],[0,-25,25],[0,-26,26],[1,-27,26],[2,-26,24],[4,-27,23],[6,-28,22],[7,-27,20],[8,-28,20],[8,-29,21],[10,-30,20],[11,-32,21],[12,-34,22],[14,-35,21],[14,-36,22],[15,-37,22],[16,-36,20],[15,-34,19],[16,-34,18],[16,-33,17],[18,-34,16],[19,-33,14],[20,-34,14],[21,-34,13],[20,-32,12],[21,-31,10],[22,-30,8],[21,-28,7],[22,-28,6],[23,-29,6],[24,-28,4],[26,-29,3],[28,-30,2],[29,-29,0],[30,-30,0],[31,-30,-1],[30,-28,-2],[28,-27,-1],[28,-26,-2],[27,-25,-2],[28,-24,-4],[27,-22,-5],[28,-22,-6],[28,-21,-7],[26,-20,-6],[25,-18,-7],[24,-16,-8],[22,-15,-7],[22,-14,-8],[23,-14,-9],[22,-12,-10],[23,-11,-12],[24,-10,-14],[23,-8,-15],[24,-8,-16],[24,-7,-17],[26,-8,-18],[27,-7,-20],[28,-8,-20],[29,-8,-21],[28,-6,-22],[26,-5,-21],[26,-4,-22],[25,-3,-22],[26,-2,-24],[25,0,-25],[26,0,-26],[26,1,-27],[24,2,-26],[23,4,-27],[22,6,-28],[20,7,-27],[20,8,-28],[21,8,-29],[20,10,-30],[21,11,-32],[22,12,-34],[21,14,-35],[22,14,-36],[22,15,-37],[20,16,-36],[19,15,-34],[18,16,-34],[17,16,-33],[16,18,-34],[14,19,-33],[14,20,-34],[13,21,-34],[12,20,-32],[10,21,-31],[8,22,-30],[7,21,-28],[6,22,-28],[6,23,-29],[4,24,-28],[3,26,-29],[2,28,-30],[0,29,-29],[0,30,-30],[-1,31,-30],[-2,30,-28],[-1,28,-27],[-2,28,-26],[-2,27,-25],[-4,28,-24],[-5,27,-22],[-6,28,-22],[-7,28,-21],[-6,26,-20],[-7,25,-18],[-8,24,-16],[-7,22,-15],[-8,22,-14],[-9,23,-14],[-10,22,-12],[-12,23,-11],[-14,24,-10],[-15,26,-11],[-16,26,-10],[-17,27,-10],[-18,26,-8],[-17,24,-7],[-16,22,-6],[-17,21,-4],[-18,22,-4],[-19,22,-3],[-20,22,-2],[-20,21,-1],[-22,22,0],[-23,21,2],[-24,20,4],[-23,18,5],[-22,16,6],[-20,15,5]];
const CERTIFIED_TURTLE_PLACEMENTS = ["turtle:1:3,-1,-2","turtle:3:2,-5,3","turtle:4:-5,3,2","turtle:3:-2,3,-1","turtle:10:7,-3,-4","turtle:6:-3,-4,7","turtle:0:5,4,-9","turtle:10:-5,3,2","turtle:3:4,-9,5","turtle:3:-10,1,9","turtle:4:7,-3,-4","turtle:3:-4,7,-3","turtle:0:-3,-4,7","turtle:9:-10,1,9","turtle:9:12,-1,-11","turtle:10:-1,-11,12","turtle:9:4,-9,5","turtle:4:-1,-11,12","turtle:10:1,9,-10","turtle:6:5,4,-9","turtle:10:5,7,-12","turtle:3:12,-1,-11","turtle:11:9,8,-17","turtle:10:13,3,-16","turtle:6:-11,12,-1","turtle:6:-13,10,3","turtle:8:-12,5,7","turtle:6:-17,6,11","turtle:9:-16,13,3","turtle:6:9,-10,1","turtle:6:7,-12,5","turtle:8:8,-17,9","turtle:6:3,-16,13","turtle:6:11,-8,-3","turtle:8:16,-9,-7","turtle:9:18,-13,-5","turtle:10:15,-19,4","turtle:6:15,-4,-11","turtle:3:18,-13,-5","turtle:3:10,-21,11","turtle:8:-6,11,-5","turtle:6:-7,16,-9","turtle:6:-5,18,-13","turtle:9:4,15,-19","turtle:9:-10,19,-9","turtle:4:-15,17,-2","turtle:0:11,10,-21","turtle:9:-8,-3,11","turtle:7:-9,-7,16","turtle:10:-13,-5,18","turtle:6:-19,4,15","turtle:9:-4,-11,15","turtle:4:-13,-5,18","turtle:4:-21,11,10","turtle:6:1,-18,17","turtle:10:17,1,-18","turtle:9:-2,-15,17","turtle:6:-11,-12,23","turtle:8:2,-23,21","turtle:4:-7,-17,24","turtle:6:-3,-22,25","turtle:6:17,-2,-15","turtle:10:23,-11,-12","turtle:11:21,2,-23","turtle:3:24,-7,-17","turtle:10:25,-3,-22","turtle:9:2,19,-21","turtle:3:-10,19,-9","turtle:4:5,19,-24","turtle:4:-7,25,-18","turtle:7:-3,23,-20","turtle:10:5,19,-24","turtle:9:-2,27,-25","turtle:9:16,9,-25","turtle:0:13,12,-25","turtle:0:23,4,-27","turtle:9:10,21,-31","turtle:0:3,26,-29","turtle:2:12,17,-29","turtle:3:16,9,-25","turtle:0:17,16,-33","turtle:10:21,11,-32","turtle:10:9,-25,16","turtle:3:4,-27,23","turtle:9:-18,17,1","turtle:10:19,-21,2","turtle:0:19,-24,5","turtle:3:12,-25,13","turtle:0:25,-18,-7","turtle:11:23,-20,-3","turtle:6:19,-24,5","turtle:10:27,-25,-2","turtle:10:21,-31,10","turtle:1:17,-29,12","turtle:4:9,-25,16","turtle:3:26,-29,3","turtle:6:11,-32,21","turtle:3:16,-33,17","turtle:10:-15,17,-2","turtle:6:-17,24,-7","turtle:7:-23,21,2"];

const tileRegistry = new Map([
  ["turtle", { id: "turtle", name: "Turtle", loop: A2_TILE_LOOPS.turtle.map(p => [...p]), color: "#247f89" }],
  ["hat", { id: "hat", name: "Hat", loop: A2_TILE_LOOPS.hat.map(p => [...p]), color: "#e59a3a" }]
]);
const selectedTileIds = new Set(["turtle"]);
let nextCustomTile = 1;
let mode = "growth";
let boundaryPreset = "certified";
let boundary = CERTIFIED_TURTLE_BOUNDARY.map(point => [...point]);
let boundaryClosed = true;
let placements = [];
let seed = null;
let running = false;
let stopToken = { stop: false };
let searchGhost = null;
let learnedSupport = [];
let draftLoop = [];
let draftClosed = false;
let camera = { zoom: 1, x: 0, y: 0 };
let dragging = false;
let dragPoint = null;
const comparisonRuns = new Map();
let growthWorker = null;
let growthSequence = 0;
let growthRunning = false;
const growthSeries = new Map();

const modeButtons = [...document.querySelectorAll(".mode-button")];
const presetButtons = [...document.querySelectorAll("[data-preset]")];
const tilePresetButtons = [...document.querySelectorAll("[data-tile-preset]")];

const axial = ([x, y]) => ({ x: x + y * 0.5, y: -y * sqrt3 / 2 });
const polygonArea2 = loop => Math.abs(loop.reduce((sum, p, index) => {
  const next = loop[(index + 1) % loop.length];
  return sum + p[0] * next[1] - next[0] * p[1];
}, 0));

function boundsFor(loops) {
  const points = loops.flat().map(axial);
  if (!points.length) return { minX: -10, maxX: 10, minY: -10, maxY: 10 };
  return {
    minX: Math.min(...points.map(p => p.x)), maxX: Math.max(...points.map(p => p.x)),
    minY: Math.min(...points.map(p => p.y)), maxY: Math.max(...points.map(p => p.y))
  };
}

function makeTransform(loops, targetCanvas, useCamera = false) {
  const b = boundsFor(loops);
  const width = targetCanvas.clientWidth || targetCanvas.width;
  const height = targetCanvas.clientHeight || targetCanvas.height;
  const padding = 58;
  const fit = Math.min((width - padding * 2) / (b.maxX - b.minX || 1), (height - padding * 2) / (b.maxY - b.minY || 1));
  return point => {
    const p = axial(point);
    const baseX = padding + (p.x - b.minX) * fit;
    const baseY = padding + (p.y - b.minY) * fit;
    if (!useCamera) return { x: baseX, y: baseY };
    return {
      x: width / 2 + (baseX - width / 2) * camera.zoom + camera.x,
      y: height / 2 + (baseY - height / 2) * camera.zoom + camera.y
    };
  };
}

function drawPolygon(context, loop, transform, fill, stroke = "#23312e", width = 1.2, dashed = false) {
  if (!loop?.length) return;
  context.save();
  context.beginPath();
  loop.forEach((point, index) => {
    const p = transform(point);
    index ? context.lineTo(p.x, p.y) : context.moveTo(p.x, p.y);
  });
  context.closePath();
  if (fill) { context.fillStyle = fill; context.fill(); }
  context.strokeStyle = stroke;
  context.lineWidth = width;
  if (dashed) context.setLineDash([7, 5]);
  context.stroke();
  context.restore();
}

function activeBoundary() {
  return mode === "growth" ? makeHexBoundary(+$('radiusInput').value) : boundary;
}

function seedLoop() {
  const seedId = $("seedSelect").value;
  if (seedId === "none") return null;
  if (seedId === "hexagon") return A2_TILE_LOOPS.hexagon.map(p => [...p]);
  if (seedId === "turtle") {
    const orientation = tileOrientations("turtle", A2_TILE_LOOPS.turtle)[1];
    return A2_TILE_LOOPS.turtle.map(point => a2Transform(point, orientation.symmetry));
  }
  return tileRegistry.get(seedId)?.loop.map(p => [...p]) || null;
}

function drawGrid(context, transform, frame, targetCanvas) {
  const radius = Math.max(12, ...frame.map(p => Math.max(Math.abs(p[0]), Math.abs(p[1]), Math.abs(p[2]))));
  const step = radius > 65 ? 4 : radius > 38 ? 2 : 1;
  context.fillStyle = "rgba(70,90,84,.17)";
  for (let x = -radius; x <= radius; x += step) for (let y = -radius; y <= radius; y += step) {
    const point = [x, y, -x - y];
    const p = transform(point);
    if (p.x < 0 || p.y < 0 || p.x > targetCanvas.clientWidth || p.y > targetCanvas.clientHeight) continue;
    context.beginPath(); context.arc(p.x, p.y, 1.1, 0, Math.PI * 2); context.fill();
  }
}

function drawLearnedMarks(transform) {
  if (!$("showMarking").checked || !learnedSupport.length) return;
  for (const placement of placements) {
    for (const mark of learnedSupport) {
      if (mark.tile !== placement.tile) continue;
      const global = a2Add(a2Transform(mark.point, placement.orientation.symmetry), placement.translation);
      const p = transform(global);
      ctx.beginPath();
      ctx.arc(p.x, p.y, Math.max(2.3, Math.min(5, 3.2 * camera.zoom)), 0, Math.PI * 2);
      ctx.fillStyle = mark.color === 0 ? "#707a76" : palette[(mark.color - 1) % palette.length];
      ctx.fill();
      ctx.strokeStyle = "rgba(255,255,255,.9)";
      ctx.lineWidth = 1;
      ctx.stroke();
    }
  }
}

function resizeCanvas(target, context) {
  const ratio = devicePixelRatio || 1;
  const width = target.clientWidth || 900;
  const height = target.clientHeight || 620;
  if (target.width !== Math.floor(width * ratio) || target.height !== Math.floor(height * ratio)) {
    target.width = Math.floor(width * ratio); target.height = Math.floor(height * ratio);
  }
  context.setTransform(ratio, 0, 0, ratio, 0, 0);
  return { width, height };
}

function draw() {
  const { width, height } = resizeCanvas(canvas, ctx);
  ctx.clearRect(0, 0, width, height);
  ctx.fillStyle = "#edf2f0"; ctx.fillRect(0, 0, width, height);
  const region = activeBoundary();
  const frame = region.length ? region : makeHexBoundary(20);
  const loops = [frame, ...placements.map(p => p.loop), ...(seed ? [seed.loop] : []), ...(searchGhost?.placement ? [searchGhost.placement.loop] : [])];
  const transform = makeTransform(loops, canvas, true);
  if (region.length) drawPolygon(ctx, region, transform, "rgba(255,255,255,.74)", "#90a39e", 2);
  drawGrid(ctx, transform, frame, canvas);
  placements.forEach((placement, index) => {
    const tile = tileRegistry.get(placement.tile);
    const color = tile?.color || palette[index % palette.length];
    drawPolygon(ctx, placement.loop, transform, `${color}${index % 2 ? "dd" : "f2"}`, "#fff", 1);
  });
  if (seed) drawPolygon(ctx, seed.loop, transform, "#7a6aa6", "#463963", 2);
  drawLearnedMarks(transform);
  if (searchGhost?.placement) {
    const trial = searchGhost.kind === "trial";
    drawPolygon(ctx, searchGhost.placement.loop, transform, trial ? "rgba(34,166,120,.30)" : "rgba(210,67,67,.34)", trial ? "#16805e" : "#be3434", 3, !trial);
  }
  if (mode === "region" && !boundaryClosed && boundary.length) {
    ctx.beginPath();
    boundary.forEach((point, index) => { const p = transform(point); index ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y); });
    ctx.strokeStyle = "#7a6aa6"; ctx.lineWidth = 3; ctx.stroke();
    boundary.forEach((point, index) => { const p = transform(point); ctx.beginPath(); ctx.arc(p.x, p.y, index ? 4 : 7, 0, Math.PI * 2); ctx.fillStyle = index ? "#fff" : "#7a6aa6"; ctx.fill(); ctx.strokeStyle = "#7a6aa6"; ctx.stroke(); });
  }
}

function loopIsSimple(loop) {
  if (loop.length < 3 || polygonArea2(loop) < 1e-7) return false;
  const cross = (a, b, c) => (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0]);
  const onSegment = (a, b, p) => Math.abs(cross(a, b, p)) < 1e-8 && p[0] >= Math.min(a[0], b[0]) && p[0] <= Math.max(a[0], b[0]) && p[1] >= Math.min(a[1], b[1]) && p[1] <= Math.max(a[1], b[1]);
  const intersects = (a, b, c, d) => {
    const abC = cross(a, b, c), abD = cross(a, b, d), cdA = cross(c, d, a), cdB = cross(c, d, b);
    if ((abC > 0) !== (abD > 0) && (cdA > 0) !== (cdB > 0)) return true;
    return (Math.abs(abC) < 1e-8 && onSegment(a, b, c)) || (Math.abs(abD) < 1e-8 && onSegment(a, b, d)) || (Math.abs(cdA) < 1e-8 && onSegment(c, d, a)) || (Math.abs(cdB) < 1e-8 && onSegment(c, d, b));
  };
  for (let i = 0; i < loop.length; i++) for (let j = i + 1; j < loop.length; j++) {
    if (j === i + 1 || (i === 0 && j === loop.length - 1)) continue;
    const a = loop[i], b = loop[(i + 1) % loop.length], c = loop[j], d = loop[(j + 1) % loop.length];
    if (intersects(a, b, c, d)) return false;
  }
  return true;
}

const gcd = (a, b) => { a = Math.abs(a); b = Math.abs(b); while (b) [a, b] = [b, a % b]; return a || 1; };
const primitiveDirection = (a, b) => {
  const delta = [b[0] - a[0], b[1] - a[1], b[2] - a[2]];
  const divisor = gcd(gcd(delta[0], delta[1]), delta[2]);
  const direction = delta.map(value => value / divisor);
  const first = direction.find(value => value !== 0) || 1;
  return (first < 0 ? direction.map(value => -value) : direction).join(",");
};

function availableBoundaryDirections(tileIds) {
  const directions = new Set();
  for (const id of tileIds) {
    const loop = tileRegistry.get(id)?.loop; if (!loop) continue;
    for (const orientation of tileOrientations(id, loop)) for (let index = 0; index < orientation.loop.length; index++) directions.add(primitiveDirection(orientation.loop[index], orientation.loop[(index + 1) % orientation.loop.length]));
  }
  return directions;
}

function areaIsRepresentable(area, tileIds) {
  const units = [...new Set(tileIds.map(id => polygonArea2(tileRegistry.get(id)?.loop || [])).filter(value => Number.isInteger(value) && value > 0))];
  if (!Number.isInteger(area) || !units.length) return false;
  const reachable = new Uint8Array(area + 1); reachable[0] = 1;
  for (let value = 0; value <= area; value++) if (reachable[value]) for (const unit of units) if (value + unit <= area) reachable[value + unit] = 1;
  return !!reachable[area];
}

function cornerAngleWeights(loop) {
  const points = loop.map(([x, y]) => ({ x: x + y * 0.5, y: y * sqrt3 / 2 }));
  const signedArea = points.reduce((sum, point, index) => { const next = points[(index + 1) % points.length]; return sum + point.x * next.y - next.x * point.y; }, 0);
  const orientation = Math.sign(signedArea) || 1;
  return points.map((point, index) => {
    const previous = points[(index - 1 + points.length) % points.length], next = points[(index + 1) % points.length];
    const incoming = [point.x - previous.x, point.y - previous.y], outgoing = [next.x - point.x, next.y - point.y];
    let turn = Math.atan2(incoming[0] * outgoing[1] - incoming[1] * outgoing[0], incoming[0] * outgoing[0] + incoming[1] * outgoing[1]);
    if (orientation < 0) turn = -turn;
    let interior = Math.PI - turn; if (interior <= 0) interior += Math.PI * 2;
    return Math.round(interior * 6 / Math.PI);
  });
}

function unsupportedCornerCount(loop, tileIds) {
  const contributions = new Set([6]);
  for (const id of tileIds) for (const weight of cornerAngleWeights(tileRegistry.get(id)?.loop || [])) if (weight > 0 && weight < 12) contributions.add(weight);
  const reachable = new Uint8Array(13); reachable[0] = 1;
  for (let value = 0; value <= 12; value++) if (reachable[value]) for (const contribution of contributions) if (value + contribution <= 12) reachable[value + contribution] = 1;
  return cornerAngleWeights(loop).filter(weight => weight <= 0 || weight >= 12 || !reachable[weight]).length;
}

function isTranslationalFundamentalPolygon(loop) {
  if (![4, 6].includes(loop.length)) return false;
  const points = loop.map(axial), signs = [];
  for (let index = 0; index < points.length; index++) {
    const a = points[index], b = points[(index + 1) % points.length], c = points[(index + 2) % points.length];
    const turn = (b.x - a.x) * (c.y - b.y) - (b.y - a.y) * (c.x - b.x);
    if (Math.abs(turn) > 1e-8) signs.push(Math.sign(turn));
  }
  if (!signs.length || signs.some(sign => sign !== signs[0])) return false;
  const half = loop.length / 2;
  for (let index = 0; index < half; index++) {
    const a = loop[index], b = loop[(index + 1) % loop.length], c = loop[index + half], d = loop[(index + half + 1) % loop.length];
    if (b.some((value, axis) => value - a[axis] !== c[axis] - d[axis])) return false;
  }
  return true;
}

function assessRegion() {
  const tileIds = selectedTiles(), blockers = [], notes = [], area = polygonArea2(boundary);
  if (!boundaryClosed || !loopIsSimple(boundary)) blockers.push("Boundary must be one closed simple loop.");
  if (!areaIsRepresentable(area, tileIds)) blockers.push(`Area ${area} is not a nonnegative integer combination of ${tileIds.map(id => polygonArea2(tileRegistry.get(id)?.loop || [])).join(" and ") || "the selected tile areas"}.`);
  const directions = availableBoundaryDirections(tileIds), unsupported = boundary.filter((point, index) => !directions.has(primitiveDirection(point, boundary[(index + 1) % boundary.length]))).length;
  if (unsupported) blockers.push(`${unsupported} boundary segment${unsupported === 1 ? " uses" : "s use"} a direction unavailable on the selected tiles.`);
  const unsupportedCorners = boundary.length >= 3 ? unsupportedCornerCount(boundary, tileIds) : 0;
  if (unsupportedCorners) blockers.push(`${unsupportedCorners} boundary corner${unsupportedCorners === 1 ? " has" : "s have"} an angle that cannot be assembled from selected-tile corner contributions.`);
  if (tileIds.length === 1 && ["hat", "turtle"].includes(tileIds[0]) && isTranslationalFundamentalPolygon(boundary)) blockers.push(`A tiled ${boundary.length === 6 ? "centrally symmetric hexagon" : "parallelogram"} would repeat by translations and create a periodic ${tileRegistry.get(tileIds[0]).name} tiling.`);
  if (boundaryPreset === "certified" && tileIds.includes("turtle")) notes.push("Certified: this is the outer boundary of a verified 101-Turtle patch.");
  else if (!blockers.length) notes.push("Not ruled out, but only search can decide it. Patch, corona, and substitution-supertile boundaries are the strongest candidates.");
  return { blockers, notes, area };
}

function renderRegionAssessment() {
  const target = $("regionAssessment"); if (!target) return;
  const assessment = assessRegion(), blocked = assessment.blockers.length > 0;
  target.dataset.state = blocked ? "blocked" : "promising";
  const heading = document.createElement("strong"); heading.textContent = blocked ? "Ruled out before search" : "Region has a chance";
  const list = document.createElement("ul");
  for (const message of [...assessment.blockers, ...assessment.notes]) { const item = document.createElement("li"); item.textContent = message; list.append(item); }
  target.replaceChildren(heading, list);
}

function svgThumbnail(tile) {
  const points = tile.loop.map(axial);
  const b = boundsFor([tile.loop]);
  const scale = Math.min(80 / (b.maxX - b.minX || 1), 54 / (b.maxY - b.minY || 1));
  const polygon = points.map(p => `${10 + (p.x - b.minX) * scale},${7 + (p.y - b.minY) * scale}`).join(" ");
  return `<svg viewBox="0 0 100 68" aria-hidden="true"><polygon points="${polygon}" fill="${tile.color}" stroke="#fff" stroke-width="2"/></svg>`;
}

function renderTileLibrary() {
  const selected = $("selectedTileList");
  const catalog = $("tileCatalog");
  selected.replaceChildren(); catalog.replaceChildren();
  for (const id of selectedTileIds) {
    const tile = tileRegistry.get(id); if (!tile) continue;
    const row = document.createElement("div"); row.className = "selected-tile";
    row.innerHTML = `${svgThumbnail(tile)}<strong>${tile.name}</strong>`;
    const remove = document.createElement("button"); remove.type = "button"; remove.textContent = "×"; remove.setAttribute("aria-label", `Remove ${tile.name}`);
    remove.addEventListener("click", () => { selectedTileIds.delete(id); renderTileLibrary(); updateCapacity(); });
    row.append(remove); selected.append(row);
  }
  for (const tile of tileRegistry.values()) {
    const button = document.createElement("button"); button.type = "button"; button.className = "catalog-tile";
    button.setAttribute("aria-pressed", String(selectedTileIds.has(tile.id)));
    button.innerHTML = `${svgThumbnail(tile)}<strong>${tile.name}</strong>`;
    button.addEventListener("click", () => { selectedTileIds.has(tile.id) ? selectedTileIds.delete(tile.id) : selectedTileIds.add(tile.id); renderTileLibrary(); updateCapacity(); });
    catalog.append(button);
  }
}

function refreshSeedOptions() {
  const select = $("seedSelect");
  const current = select.value || "turtle";
  select.replaceChildren();
  for (const tile of tileRegistry.values()) select.add(new Option(tile.name, tile.id));
  select.add(new Option("Hexagon", "hexagon")); select.add(new Option("No seed", "none"));
  select.value = [...select.options].some(option => option.value === current) ? current : "turtle";
}

function updateCapacity() {
  const areas = [...selectedTileIds].map(id => polygonArea2(tileRegistry.get(id)?.loop || [])).filter(Boolean);
  const unit = Math.min(...areas, 33);
  const growthArea = polygonArea2(makeHexBoundary(+$('radiusInput').value)) - polygonArea2(seedLoop() || []);
  const regionArea = polygonArea2(boundary);
  $("growthCapacity").textContent = `Target ${growthTarget().toLocaleString()} tiles. The outline sets scale only; it never blocks growth.`;
  $("regionCapacity").textContent = `Current boundary has room for roughly ${Math.max(0, Math.floor(regionArea / unit)).toLocaleString()} selected tiles.`;
  renderRegionAssessment();
}

function growthTarget() {
  const areas = [...selectedTileIds].map(id => polygonArea2(tileRegistry.get(id)?.loop || [])).filter(Boolean);
  const unit = Math.min(...areas, 33);
  const area = polygonArea2(makeHexBoundary(+$('radiusInput').value)) - polygonArea2(seedLoop() || []);
  return Math.max(100, Math.min(1500, Math.floor(area / unit * 0.65)));
}

function updateBoundaryState() {
  $("boundaryState").textContent = boundaryClosed ? (loopIsSimple(boundary) ? `${boundary.length} vertices · closed` : `${boundary.length} vertices · invalid`) : `${boundary.length} vertices · open`;
}

function setMode(next) {
  if (growthRunning) stopGrowthBenchmark("Comparison stopped because the problem changed.");
  mode = next;
  modeButtons.forEach(button => button.classList.toggle("active", button.dataset.mode === mode));
  $("growthControls").hidden = mode !== "growth"; $("regionControls").hidden = mode !== "region";
  placements = []; seed = null; searchGhost = null; camera = { zoom: 1, x: 0, y: 0 };
  updateBoundaryState(); updateCapacity(); draw();
}

function selectedTiles() { return [...selectedTileIds]; }
function customTilePayload() { return Object.fromEntries([...tileRegistry].map(([id, tile]) => [id, tile.loop])); }

const SVG_NS = "http://www.w3.org/2000/svg";
const GROWTH_MODES = [
  { id: "naive", label: "Naive" },
  { id: "gcts", label: "GCTS cluster memo" },
  { id: "gcts-rl", label: "GCTS + learned clusters" }
];
const svgNode = (name, attributes = {}, content = null) => {
  const node = document.createElementNS(SVG_NS, name);
  for (const [key, value] of Object.entries(attributes)) node.setAttribute(key, String(value));
  if (content != null) node.textContent = content;
  return node;
};
function niceGrowthMaximum(value, ticks = 4) {
  if (!Number.isFinite(value) || value <= 0) return ticks;
  const rough = value / ticks, power = 10 ** Math.floor(Math.log10(rough)), fraction = rough / power;
  const step = (fraction <= 1 ? 1 : fraction <= 2 ? 2 : fraction <= 5 ? 5 : 10) * power;
  return Math.ceil(value / step) * step;
}
function renderGrowthChart() {
  const chart = $("growthChart"); chart.replaceChildren();
  const allPoints = [...growthSeries.values()].flatMap(series => series.points ?? []);
  if (!allPoints.length) { chart.append(svgNode("text", { class: "growth-empty", x: 380, y: 106, "text-anchor": "middle" }, "Run the comparison to measure this tile system.")); return; }
  const width = 760, height = 210, margin = { left: 48, right: 18, top: 37, bottom: 31 };
  const plotWidth = width - margin.left - margin.right, plotHeight = height - margin.top - margin.bottom;
  const maxMs = niceGrowthMaximum(Math.max(1, ...allPoints.map(point => point.milliseconds)), 5);
  const maxTiles = Math.max(4, Math.ceil(Math.max(...allPoints.map(point => point.tiles)) / 4) * 4);
  const x = ms => margin.left + Math.max(0, ms) / maxMs * plotWidth;
  const y = tiles => margin.top + plotHeight - Math.max(0, tiles) / maxTiles * plotHeight;
  chart.append(svgNode("title", {}, "Measured A2 tiling growth curves"), svgNode("desc", {}, "Greatest tile count reached over wall-clock time for naive search, online geometric GCTS, and GCTS guided by learned local cluster proposals."));
  for (let index = 0; index <= 4; index++) {
    const value = maxTiles * index / 4, yy = y(value);
    chart.append(svgNode("line", { class: "growth-grid", x1: margin.left, y1: yy, x2: width - margin.right, y2: yy }), svgNode("text", { class: "growth-tick", x: margin.left - 8, y: yy + 4, "text-anchor": "end" }, value));
  }
  for (let index = 0; index <= 5; index++) {
    const value = maxMs * index / 5, xx = x(value);
    chart.append(svgNode("line", { class: "growth-grid", x1: xx, y1: margin.top, x2: xx, y2: margin.top + plotHeight }), svgNode("text", { class: "growth-tick", x: xx, y: height - 12, "text-anchor": "middle" }, (value / 1000).toFixed(value < 1000 ? 2 : 1)));
  }
  chart.append(svgNode("line", { class: "growth-axis", x1: margin.left, y1: margin.top + plotHeight, x2: width - margin.right, y2: margin.top + plotHeight }), svgNode("line", { class: "growth-axis", x1: margin.left, y1: margin.top, x2: margin.left, y2: margin.top + plotHeight }), svgNode("text", { class: "growth-axis-label", x: margin.left + plotWidth / 2, y: height - 1, "text-anchor": "middle" }, "elapsed time (seconds)"), svgNode("text", { class: "growth-axis-label", x: 12, y: margin.top + plotHeight / 2, transform: `rotate(-90 12 ${margin.top + plotHeight / 2})`, "text-anchor": "middle" }, "tiles"));
  GROWTH_MODES.forEach((mode, index) => {
    const xx = margin.left + index * 184;
    chart.append(svgNode("line", { class: `growth-series growth-series-${mode.id}`, x1: xx, y1: 14, x2: xx + 24, y2: 14 }), svgNode("text", { class: "growth-legend", x: xx + 30, y: 18 }, mode.label));
  });
  for (const mode of GROWTH_MODES) {
    const series = growthSeries.get(mode.id), points = series?.points ?? [];
    if (!points.length) continue;
    let path = `M ${x(points[0].milliseconds)} ${y(points[0].tiles)}`;
    for (let index = 1; index < points.length; index++) path += ` H ${x(points[index].milliseconds)} V ${y(points[index].tiles)}`;
    path += ` H ${x(Math.min(series?.result?.milliseconds ?? points.at(-1).milliseconds, maxMs))}`;
    chart.append(svgNode("path", { class: `growth-series growth-series-${mode.id}`, d: path }));
    for (const point of points) {
      const className = `growth-marker growth-marker-${mode.id}`, xx = x(point.milliseconds), yy = y(point.tiles);
      if (mode.id === "naive") chart.append(svgNode("rect", { class: className, x: xx - 3, y: yy - 3, width: 6, height: 6 }));
      else if (mode.id === "gcts-rl") chart.append(svgNode("path", { class: className, d: `M ${xx} ${yy - 4} L ${xx + 4} ${yy + 3} L ${xx - 4} ${yy + 3} Z` }));
      else chart.append(svgNode("circle", { class: className, cx: xx, cy: yy, r: 3.2 }));
    }
  }
}
const formatBenchmarkTime = milliseconds => milliseconds < 1000 ? `${milliseconds}ms` : `${(milliseconds / 1000).toFixed(2)}s`;
function stopGrowthBenchmark(message = "Comparison stopped.") {
  growthSequence++;
  growthWorker?.postMessage({ type: "stop" }); growthWorker?.terminate(); growthWorker = null;
  growthRunning = false; $("growthBenchmarkButton").textContent = "Compare growth"; $("growthBenchmarkStatus").textContent = message;
}
function startGrowthBenchmark() {
  if (mode !== "growth") { $("growthBenchmarkStatus").textContent = "Growth curves apply to Grow outward mode."; return; }
  if (running) { $("growthBenchmarkStatus").textContent = "Stop the live search before starting a controlled comparison."; return; }
  const tiles = selectedTiles();
  if (!tiles.length) { $("growthBenchmarkStatus").textContent = "Select at least one tile first."; return; }
  if (growthWorker) stopGrowthBenchmark();
  growthSeries.clear(); renderGrowthChart(); growthSequence++;
  const sequence = growthSequence, target = growthTarget();
  growthRunning = true; $("growthBenchmarkButton").textContent = "Stop comparison"; $("growthBenchmarkStatus").textContent = `Measuring naive growth toward ${target.toLocaleString()} tiles…`;
  growthWorker = new Worker(new URL("./growth-benchmark-worker.js?v=20260721-frontier-memo", import.meta.url), { type: "module" });
  growthWorker.addEventListener("message", event => {
    const message = event.data ?? {}; if (message.sequence !== sequence) return;
    if (message.type === "series-start") { growthSeries.set(message.mode.id, { points: [] }); $("growthBenchmarkStatus").textContent = `Measuring ${message.mode.label}…`; }
    else if (message.type === "sample") { const series = growthSeries.get(message.mode) ?? { points: [] }; series.points.push(message.point); growthSeries.set(message.mode, series); renderGrowthChart(); }
    else if (message.type === "series-finished") { const series = growthSeries.get(message.result.mode) ?? { points: [] }; series.result = message.result; if (!series.points.length) series.points = message.result.points ?? []; growthSeries.set(message.result.mode, series); renderGrowthChart(); }
    else if (message.type === "finished") {
      growthWorker?.terminate(); growthWorker = null; growthRunning = false; $("growthBenchmarkButton").textContent = "Compare growth";
      $("growthBenchmarkStatus").textContent = (message.results ?? []).map(result => {
        const reached = result.points?.find(point => point.tiles >= target);
        return reached ? `${result.label} ${formatBenchmarkTime(reached.milliseconds)}` : `${result.label} ${result.tileCount} tiles / ${formatBenchmarkTime(result.milliseconds)}`;
      }).join(" · ") + ` · ${message.learnedClusterCount ?? 0} cluster relations learned`;
      renderGrowthChart();
    } else if (message.type === "error") stopGrowthBenchmark(`Comparison error: ${message.error}`);
  });
  growthWorker.addEventListener("error", error => stopGrowthBenchmark(`Comparison error: ${error.message}`));
  growthWorker.postMessage({ type: "start", sequence, config: { boundary: activeBoundary(), seedLoop: seedLoop(), tiles, customTiles: customTilePayload(), targetPlacements: target, nodeLimit: 100000, timeLimitMs: 15000, randomSeed: 4, maxRank: Number($("rankCeiling").value) || 3 } });
}

function recordComparison(key, strategy, result) {
  const comparison = comparisonRuns.get(key) || {};
  comparison[strategy === "geometry" ? "geometry" : "gcts"] = {
    nodes: result.stats.nodes, backtracks: result.stats.backtracks, memoHits: result.stats.prunes || 0
  };
  comparisonRuns.set(key, comparison);
  if (comparison.geometry && comparison.gcts) {
    const saved = comparison.geometry.nodes - comparison.gcts.nodes;
    const percent = comparison.geometry.nodes ? Math.round(saved / comparison.geometry.nodes * 100) : 0;
    $("comparisonStatus").textContent = saved > 0
      ? `Deterministic A/B · GCTS visited ${comparison.gcts.nodes.toLocaleString()} nodes versus ${comparison.geometry.nodes.toLocaleString()} unmarked: ${percent}% fewer nodes, with ${comparison.gcts.memoHits.toLocaleString()} geometric memo hits.`
      : `Deterministic A/B · GCTS visited ${comparison.gcts.nodes.toLocaleString()} nodes versus ${comparison.geometry.nodes.toLocaleString()} unmarked. This marking did not accelerate these settings.`;
  } else {
    const completed = comparison.geometry ? "Geometry-only baseline recorded." : `GCTS run recorded with ${comparison.gcts.memoHits.toLocaleString()} memo hits.`;
    $("comparisonStatus").textContent = `${completed} Switch the workflow and run again unchanged to complete the deterministic A/B.`;
  }
}

function updateMetrics(event) {
  $("tilesMetric").textContent = event.placed;
  $("coverageMetric").textContent = mode === "growth" ? `${Math.min(100, Math.floor(event.placed / (event.targetPlacements || growthTarget()) * 100))}%` : `${event.totalCells ? Math.floor(event.coveredCells / event.totalCells * 100) : 0}%`;
  $("nodesMetric").textContent = event.nodes; $("backtracksMetric").textContent = event.backtracks;
  $("memoMetric").textContent = event.marking.prunes || 0;
  $("marksMetric").textContent = event.marking.geometricRevision ?? event.marking.revision; $("supportMetric").textContent = event.marking.supportSites;
  const observed = event.marking.observedFailures || 0, pending = event.marking.pendingFailures || 0, encoded = event.marking.encodedFailures ?? observed - pending;
  $("markingState").textContent = observed
    ? `${event.marking.geometricRevision || encoded} cluster revisions · ${event.marking.frontierClauses || 0} frontier clauses / ${event.marking.frontierPrunes || 0} hits · rank ${event.marking.rank || 3} · ${event.marking.inequalities} local inequalities · ${encoded}/${observed} branch failures encoded`
    : "Starts empty";
  learnedSupport = event.marking.support || learnedSupport;
}

function audit(event) {
  if (!["learn", "learning-skip", "marking-reencoded"].includes(event.type)) return;
  const item = document.createElement("li");
  item.textContent = event.type === "marking-reencoded"
    ? `Revision ${event.reencoding.revision} kept all ${event.reencoding.preservedFailures} failure certificates and replaced the witness for failure ${event.reencoding.targetFailure}; all ${event.reencoding.preservedInequalities} other inequalities remain unchanged.`
    : event.type === "learn" && event.update.revision
    ? `Local revision ${event.update.revision}: rejected subtree depth ${event.update.branchDepth}, ${event.update.leafFailures} terminal failure${event.update.leafFailures === 1 ? "" : "s"}, ${event.update.subtreeSites} footprint sites; attached a reach-${event.update.reach} witness to ${event.update.frontierTiles} branch-interface tile${event.update.frontierTiles === 1 ? "" : "s"}.`
    : event.type === "learn"
    ? `Cluster revision ${event.update.geometricRevision}: retained the complete failed branch at depth ${event.update.branchDepth} in translation-relative coordinates.`
    : `Failure retained as a geometric cluster clause after all ${event.update.attempts} rank-3 witnesses were checked; it was not discarded.`;
  $("auditLog").prepend(item);
}

async function run() {
  if (running) return;
  const tiles = selectedTiles();
  if (!tiles.length) { $("status").textContent = "Select at least one tile from the catalog."; return; }
  if (mode === "region" && (!boundaryClosed || !loopIsSimple(boundary))) { $("status").textContent = "Close a simple, nonzero-area boundary first."; return; }
  if (mode === "region") {
    const assessment = assessRegion();
    if (assessment.blockers.length) { $("status").textContent = `Search skipped — ${assessment.blockers[0]}`; renderRegionAssessment(); return; }
  }
  running = true; stopToken = { stop: false }; placements = []; learnedSupport = []; searchGhost = null;
  $("auditLog").replaceChildren(); $("runButton").disabled = true; $("stopButton").disabled = false;
  const region = activeBoundary();
  const initialLoop = mode === "growth" ? seedLoop() : null;
  // The center object is a boundary condition, not a placement made by the
  // online tiler. It may be a hexagon or a custom shape, so learned tile-local
  // marking domains begin with the first actual placement around it.
  seed = initialLoop ? { tile: "seed", loop: initialLoop } : null;
  $("status").textContent = "Enumerating compatible placements…"; draw();
  try {
    const fullTarget = mode === "growth" ? growthTarget() : undefined;
    const strategy = $("markingStrategy").value;
    const rankCeiling = Number($("rankCeiling").value) || 3;
    const comparisonKey = JSON.stringify({ mode, target: fullTarget, boundary: region, seed: initialLoop, rankCeiling, tiles: tiles.map(id => [id, tileRegistry.get(id)?.loop]) });
    const solveWith = (marking, target, phase, randomSeed, nodeLimit = mode === "growth" ? 1000000 : 500000) => solveA2Tiling({
      boundary: region, seed, tiles, customTiles: customTilePayload(), maximize: mode === "growth",
      targetPlacements: target,
      preferredPlacements: mode === "region" && boundaryPreset === "certified" && tiles.includes("turtle") ? CERTIFIED_TURTLE_PLACEMENTS : [],
      nodeLimit, animationDelayMs: mode === "growth" ? 2 : 8, learningWarmupDepth: mode === "growth" ? 10 : 0, maxMarkingRevisions: Infinity, markingStagnationNodes: mode === "growth" ? 1200 : Infinity, randomSeed, marking, stopToken,
      onEvent: event => {
        placements = event.placements; updateMetrics(event); audit(event);
        const prefix = phase === "training" ? "Training · " : phase === "replay" ? "Validated online replay · " : "";
        if (event.type === "trial") { searchGhost = { kind: "trial", placement: event.candidate }; $("status").textContent = `${prefix}trying ${tileRegistry.get(event.candidate.tile)?.name || event.candidate.tile} at depth ${event.placed + 1}`; }
        else if (event.type === "placement") { searchGhost = null; $("status").textContent = `${prefix}accepted tile ${event.placed} · ${event.nodes} nodes`; }
        else if (event.type === "backtrack") { searchGhost = { kind: "backtrack", placement: event.removed }; $("status").textContent = `Dead end — removing ${tileRegistry.get(event.removed.tile)?.name || event.removed.tile}; back to depth ${event.placed}`; }
        else if (event.type === "learning-start") { $("status").textContent = `Backtracked to depth ${event.placed} · searching for a safe marking mismatch…`; }
        else if (event.type === "learning-progress") { $("status").textContent = `Testing marking witnesses… ${event.attempts.toLocaleString()} checked · Stop remains available`; }
        else if (event.type === "learn") { $("status").textContent = `Backtrack encoded as geometric revision ${event.marking.geometricRevision ?? event.marking.revision}`; }
        else if (event.type === "learning-skip") { $("status").textContent = `No safe mismatch within ${event.update.attempts.toLocaleString()} witnesses · continuing backtrack`; }
        else if (event.type === "marking-reencoded") { searchGhost = null; $("status").textContent = `Marking kept all ${event.reencoding.preservedFailures} failures · recompiled failure ${event.reencoding.targetFailure} without changing revision ${event.reencoding.revision}`; }
        draw();
      }
    });
    let result;
    if (mode === "growth" && strategy === "train-replay") {
      const learner = new OnlineA2Marking({ maxWitnessTrials: 256, yieldEvery: 32, maxRank: rankCeiling });
      const trainingTarget = Math.min(30, fullTarget);
      const validationTarget = Math.min(fullTarget, trainingTarget + 10);
      let training = null;
      const trainingSeeds = [];
      for (const trainingSeed of [4, 3]) {
        trainingSeeds.push(trainingSeed);
        training = await solveWith(learner, trainingTarget, "training", trainingSeed, 5000);
        if (stopToken.stop || learner.revision > 0) break;
        const item = document.createElement("li");
        item.textContent = `Branch order ${trainingSeed} reached the training horizon without a failed branch; trying another order to generate a geometric memo.`;
        $("auditLog").prepend(item);
      }
      if (stopToken.stop) result = training;
      else {
        placements = []; searchGhost = null; draw();
        const selection = await selectA2FrozenMarking({
          learner,
          validationSeeds: [2, 5],
          validationNodeLimit: 1200,
          solveOptions: {
            boundary: region, seed, tiles, customTiles: customTilePayload(), maximize: true,
            targetPlacements: validationTarget, learningWarmupDepth: 10,
            markingStagnationNodes: 400, stopToken
          },
          onValidation: event => {
            if (event.type === "candidate-start") {
              $("status").textContent = `Validation round ${event.round} · memo ${event.index + 1}/${event.total} · revision ${event.revision} (${event.support} support entries)…`;
            } else {
              $("status").textContent = `Revision ${event.revision}: ${event.result} after ${event.nodes} nodes · checking the next memo…`;
            }
          }
        });
        if (stopToken.stop) { result = training; }
        else {
          const selectedValidation = selection.selected;
          const selectedRevision = selectedValidation?.revision ?? 0;
          learner.checkoutRevision(selectedRevision);
          const item = document.createElement("li");
          item.textContent = selectedValidation
            ? `Trained on ${trainingSeeds.length} branch order${trainingSeeds.length === 1 ? "" : "s"}, screened ${selection.candidates.length} memo revisions, and restarted from validated revision ${selectedRevision} across ${selection.seeds.length} fresh ${validationTarget}-tile searches (${learner.support.size} support entries, ${selectedValidation.totalNodes} validation nodes). Learning remains active for later failed subtrees.`
            : `No learned revision completed the fresh ${validationTarget}-tile validation patch within budget; restarting from revision 0 with online learning active.`;
          $("auditLog").prepend(item);
          placements = []; searchGhost = null; learnedSupport = learner.stats().support; draw();
          result = await solveWith(learner, fullTarget, "replay", 4);
        }
      }
    } else {
      const marking = strategy === "geometry" ? new NoA2Marking() : new OnlineA2Marking({ maxWitnessTrials: 32, yieldEvery: 32, maxRank: rankCeiling, enableLocalInequalities: strategy === "rank-local" });
      result = await solveWith(marking, fullTarget, strategy === "geometry" ? "geometry" : "online", 4);
    }
    placements = result.placements; searchGhost = null; draw();
    recordComparison(comparisonKey, strategy, result);
    const word = placements.length === 1 ? "tile" : "tiles";
    $("status").textContent = mode === "region"
      ? result.result === "yes" ? `Yes — tiled exactly with ${placements.length} ${word}.` : result.result === "no" ? "No — exhaustive search proved this region cannot be tiled." : `Unknown — stopped after ${result.stats.nodes} nodes.`
      : `${result.result === "yes" ? "Growth target reached" : stopToken.stop ? "Stopped by user" : result.result === "no" ? "All current marked branches exhausted" : "Search budget reached"}: ${placements.length} ${word}; ${result.stats.nodes.toLocaleString()} nodes, ${result.stats.backtracks.toLocaleString()} backtracks, ${(result.stats.prunes || 0).toLocaleString()} memo hits.`;
  } catch (error) {
    console.error(error); $("status").textContent = `Search error: ${error.message}`;
  } finally {
    running = false; $("runButton").disabled = false; $("stopButton").disabled = true;
  }
}

function nearestLatticePoint(event, target, frame, range = 120) {
  const rect = target.getBoundingClientRect();
  const transform = makeTransform([frame], target, false);
  let best = null, distance = Infinity;
  for (let x = -range; x <= range; x++) for (let y = -range; y <= range; y++) {
    const point = [x, y, -x - y], p = transform(point);
    const d = Math.hypot(p.x - (event.clientX - rect.left), p.y - (event.clientY - rect.top));
    if (d < distance) { best = point; distance = d; }
  }
  return distance <= 20 ? best : null;
}

function drawBuilder() {
  const { width, height } = resizeCanvas(builderCanvas, builderCtx);
  builderCtx.clearRect(0, 0, width, height); builderCtx.fillStyle = "#edf2f0"; builderCtx.fillRect(0, 0, width, height);
  const frame = draftLoop.length ? draftLoop : makeHexBoundary(10);
  const transform = makeTransform([frame], builderCanvas, false);
  drawGrid(builderCtx, transform, makeHexBoundary(12), builderCanvas);
  if (draftLoop.length) {
    builderCtx.beginPath(); draftLoop.forEach((point, index) => { const p = transform(point); index ? builderCtx.lineTo(p.x, p.y) : builderCtx.moveTo(p.x, p.y); });
    if (draftClosed) builderCtx.closePath(); builderCtx.strokeStyle = "#177c6e"; builderCtx.lineWidth = 3; builderCtx.stroke();
    if (draftClosed) { builderCtx.fillStyle = "rgba(23,124,110,.2)"; builderCtx.fill(); }
    draftLoop.forEach((point, index) => { const p = transform(point); builderCtx.beginPath(); builderCtx.arc(p.x, p.y, index ? 4 : 7, 0, Math.PI * 2); builderCtx.fillStyle = index ? "#fff" : "#177c6e"; builderCtx.fill(); builderCtx.strokeStyle = "#177c6e"; builderCtx.stroke(); });
  }
  const valid = draftClosed && loopIsSimple(draftLoop);
  $("saveCustomTile").disabled = !valid;
  $("tileBuilderState").textContent = valid ? `${draftLoop.length} vertices · area ${polygonArea2(draftLoop)} · ready to add.` : draftClosed ? "The loop is closed but invalid or self-intersecting." : draftLoop.length ? `${draftLoop.length} vertices · click the first point to close.` : "Choose a starting point.";
}

function openBuilder() {
  draftLoop = []; draftClosed = false; drawBuilder();
  const dialog = $("customTileDialog"); typeof dialog.showModal === "function" ? dialog.showModal() : dialog.setAttribute("open", "");
}
function closeBuilder() { const dialog = $("customTileDialog"); typeof dialog.close === "function" ? dialog.close() : dialog.removeAttribute("open"); }

modeButtons.forEach(button => button.addEventListener("click", () => setMode(button.dataset.mode)));
presetButtons.forEach(button => button.addEventListener("click", () => {
  boundaryPreset = button.dataset.preset;
  if (boundaryPreset === "blank") { boundary = []; boundaryClosed = false; }
  else if (boundaryPreset === "certified") { boundary = CERTIFIED_TURTLE_BOUNDARY.map(point => [...point]); boundaryClosed = true; }
  else if (boundaryPreset === "large") { boundary = makeHexBoundary(+$('regionRadiusInput').value); boundaryClosed = true; }
  else { boundary = tileRegistry.get(boundaryPreset).loop.map(p => [...p]); boundaryClosed = true; }
  placements = []; camera = { zoom: 1, x: 0, y: 0 }; updateBoundaryState(); updateCapacity(); draw();
}));
tilePresetButtons.forEach(button => button.addEventListener("click", () => { draftLoop = A2_TILE_LOOPS[button.dataset.tilePreset].map(p => [...p]); draftClosed = true; drawBuilder(); }));

$("radiusInput").addEventListener("input", () => { $("radiusOutput").textContent = $("radiusInput").value; placements = []; updateCapacity(); draw(); });
$("regionRadiusInput").addEventListener("input", () => { $("regionRadiusOutput").textContent = $("regionRadiusInput").value; if (boundaryPreset === "large") boundary = makeHexBoundary(+$('regionRadiusInput').value); placements = []; updateBoundaryState(); updateCapacity(); draw(); });
$("seedSelect").addEventListener("change", () => { placements = []; updateCapacity(); draw(); });
$("showMarking").addEventListener("change", draw);
$("runButton").addEventListener("click", run);
$("stopButton").addEventListener("click", () => { stopToken.stop = true; $("status").textContent = "Stopping at a safe search boundary…"; });
$("growthBenchmarkButton").addEventListener("click", () => growthRunning ? stopGrowthBenchmark() : startGrowthBenchmark());
$("customTileButton").addEventListener("click", openBuilder);
$("closeTileDialog").addEventListener("click", closeBuilder);
$("customTileDialog").addEventListener("click", event => { if (event.target === $("customTileDialog")) closeBuilder(); });
$("undoTilePoint").addEventListener("click", () => { if (draftClosed) draftClosed = false; else draftLoop.pop(); drawBuilder(); });
$("clearTilePoints").addEventListener("click", () => { draftLoop = []; draftClosed = false; drawBuilder(); });
$("saveCustomTile").addEventListener("click", () => {
  if (!draftClosed || !loopIsSimple(draftLoop)) return;
  const id = `custom-${nextCustomTile++}`;
  tileRegistry.set(id, { id, name: $("customTileName").value.trim() || "Custom tile", loop: draftLoop.map(p => [...p]), color: palette[(tileRegistry.size - 2) % palette.length] });
  selectedTileIds.add(id); refreshSeedOptions(); renderTileLibrary(); updateCapacity(); closeBuilder();
});

$("undoBoundary").addEventListener("click", () => { if (boundaryClosed) boundaryClosed = false; else boundary.pop(); boundaryPreset = "drawn"; placements = []; updateBoundaryState(); updateCapacity(); draw(); });
$("clearBoundary").addEventListener("click", () => { boundary = []; boundaryClosed = false; boundaryPreset = "drawn"; placements = []; updateBoundaryState(); updateCapacity(); draw(); });

builderCanvas.addEventListener("click", event => {
  if (draftClosed) return;
  const frame = draftLoop.length ? draftLoop : makeHexBoundary(10);
  const point = nearestLatticePoint(event, builderCanvas, frame, 32); if (!point) return;
  if (draftLoop.length >= 3 && a2Key(point) === a2Key(draftLoop[0])) draftClosed = true;
  else if (!draftLoop.some(existing => a2Key(existing) === a2Key(point))) draftLoop.push(point);
  drawBuilder();
});

canvas.addEventListener("click", event => {
  if (mode !== "region" || boundaryClosed || dragging) return;
  const frame = boundary.length ? boundary : makeHexBoundary(20);
  const point = nearestLatticePoint(event, canvas, frame); if (!point) return;
  if (boundary.length >= 3 && a2Key(point) === a2Key(boundary[0])) boundaryClosed = true;
  else if (!boundary.some(existing => a2Key(existing) === a2Key(point))) boundary.push(point);
  boundaryPreset = "drawn"; updateBoundaryState(); updateCapacity(); draw();
});
canvas.addEventListener("pointerdown", event => { if (mode === "region" && !boundaryClosed) return; dragging = false; dragPoint = { x: event.clientX, y: event.clientY }; canvas.setPointerCapture(event.pointerId); });
canvas.addEventListener("pointermove", event => { if (!dragPoint) return; const dx = event.clientX - dragPoint.x, dy = event.clientY - dragPoint.y; if (Math.abs(dx) + Math.abs(dy) > 2) dragging = true; camera.x += dx; camera.y += dy; dragPoint = { x: event.clientX, y: event.clientY }; draw(); });
canvas.addEventListener("pointerup", event => { dragPoint = null; if (canvas.hasPointerCapture(event.pointerId)) canvas.releasePointerCapture(event.pointerId); setTimeout(() => { dragging = false; }, 0); });
canvas.addEventListener("wheel", event => { event.preventDefault(); camera.zoom = Math.max(.4, Math.min(8, camera.zoom * Math.exp(-event.deltaY * .001))); draw(); }, { passive: false });

new ResizeObserver(() => { draw(); if ($("customTileDialog").open) drawBuilder(); }).observe(canvas);
refreshSeedOptions(); renderTileLibrary(); updateBoundaryState(); updateCapacity(); draw();
