'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const dir=path.resolve(__dirname,'../../docs/research/gcts-rl-renewal'),api=require(path.join(dir,'native-families.js')),data=JSON.parse(fs.readFileSync(path.join(dir,'native-families-reader-001.json')));
const evidence=api.validate(data),rejected=[];
function corrupt(name,change){const bad=structuredClone(data);change(bad);try{api.validate(bad);}catch(e){rejected.push({name,reason:e.message});return;}throw Error('Accepted mutation: '+name);}
const positive=d=>d.cases[0].runs.rl,decision=d=>positive(d).policy_events[0];
corrupt('palette pin',d=>d.inventory.literal_table_sha256='0'.repeat(64));
corrupt('tile count',d=>d.inventory.tile_types++);
corrupt('donor provenance',d=>d.library[0].source.tiles[0].N++);
corrupt('source abstraction',d=>d.library[0].defaults.s0++);
corrupt('ownership duplicate',d=>d.library[0].hierarchy.children[1].leaf=0);
corrupt('root cone',d=>positive(d).certificate.pins[0][1]++);
corrupt('native membership',d=>positive(d).tiles[0].N++);
corrupt('point capacity',d=>positive(d).tiles[1]=structuredClone(positive(d).tiles[0]));
corrupt('generation',d=>positive(d).tile_generations[0]=2);
corrupt('dimension',d=>positive(d).height++);
corrupt('initial census total',d=>positive(d).initial_candidate_nodes++);
corrupt('typed binding',d=>decision(d).items[0].binding.s0++);
corrupt('bound receptor',d=>decision(d).items[0].bound_receptors.s0++);
corrupt('aggregate marking',d=>decision(d).items[0].marks[0][1]++);
corrupt('missing bounded candidate',d=>decision(d).items.pop());
corrupt('policy receptor depth',d=>decision(d).depth++);
corrupt('policy occupied state',d=>decision(d).tiles[0].N++);
corrupt('policy features',d=>decision(d).features[1][1]+=.1);
corrupt('policy score',d=>decision(d).scores[0]++);
corrupt('policy probability',d=>decision(d).probabilities[0]+=.1);
corrupt('policy choice',d=>decision(d).selected=0);
corrupt('policy gradient',d=>decision(d).gradient[0]++);
corrupt('completed member',d=>positive(d).hints[0].item.members[0][1][0]++);
corrupt('completed certificate',d=>positive(d).cluster_checks=[]);
corrupt('clock binding',d=>positive(d).total_seconds++);
corrupt('repeat median',d=>d.cases[0].timings.rl.median_seconds++);
corrupt('repeat order',d=>d.cases[0].timings.rl.samples[0].order.reverse());
corrupt('unknown turned into success',d=>d.cases[1].runs.rl.status='finite_exact_native_rectangle');
corrupt('sampled gradient',d=>d.training.episodes[0].events[0].gradient[0]++);
corrupt('sampled draw',d=>d.training.episodes[0].events[0].draw=-1);
corrupt('reward update',d=>d.training.episodes[0].update.reward++);
corrupt('updated weights',d=>d.training.episodes[0].update.weights_after[0]++);
corrupt('frozen weights',d=>d.training.weights[0]++);
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
console.log(JSON.stringify({status:'passed',evidence,mutations_rejected:rejected,reader_sha256:hash(path.join(dir,'native-families-reader-001.json')),checker_sha256:hash(path.join(dir,'native-families.js')),test_sha256:hash(__filename)}));
