'use strict';
const fs=require('fs'),path=require('path'),R=require('../../docs/research/gcts-rl-renewal/indexed-families.js'),K=require('../../docs/research/gcts-rl-renewal/quantified-receptors.js');
const data=JSON.parse(fs.readFileSync(path.join(__dirname,'../../docs/research/gcts-rl-renewal/indexed-families-reader-001.json'))),stats={...R.validate(data),kernel_certificates:0,point_mutations:0,formula_mutations:0,context_mutations:0,lifetime_mutations:0,index_mutations:0,timing_mutations:0};
function reject(fn,key){let caught=false;try{fn();}catch(e){caught=true;}if(!caught)throw Error('Corrupted reader accepted');stats[key]++;}
for(const c of data.donors.map(c=>({...c,runs:{donor:c.result}})).concat(data.cases))for(const r of Object.values(c.runs)){if(r.proof===null)continue;const record={...c,result:r};K.checkRequest(r.compact.request);stats.kernel_certificates++;
 for(const t of r.tiles){const old=t.occupancy[0][1];t.occupancy[0][1]=11;reject(()=>R.check(record),'point_mutations');t.occupancy[0][1]=old;const layers=new Map();for(const m of t.marks){const layer=m[0][1]===-2?'flow':m[0][0]===-1000?'scope':m[0][1]===1?'context':m[0][0]===2*t.key[0]?'output':'premise';if(!layers.has(layer))layers.set(layer,m);}for(const m of layers.values()){const old=m[1];m[1]='!';reject(()=>R.check(record),'point_mutations');m[1]=old;}}
 for(const cmd of r.compact.request.proof){const old=cmd.formula;cmd.formula=['bot'];reject(()=>K.checkRequest(r.compact.request),'formula_mutations');cmd.formula=old;}
 const p=r.compact,old=p.request.theory;p.request.theory={...old,axioms:{...old.axioms,cheat:['imp',['bot'],['bot']]}};reject(()=>R.check(record),'context_mutations');p.request.theory=old;
 for(const row of r.timeline){const old=row.hint_in;row.hint_in=99999;reject(()=>R.trace(c,r,data.library),'lifetime_mutations');row.hint_in=old;const phase=row.entry_review.phase;row.entry_review.phase='!';reject(()=>R.trace(c,r,data.library),'lifetime_mutations');row.entry_review.phase=phase;}
 if(r.index){const ix=r.index,first=Object.values(ix.nodes).find(n=>n.rows.length);if(first){const row=first.rows.pop();reject(()=>R.index(c,r),'index_mutations');first.rows.push(row);}const hit=ix.metrics.query_cache_hits||0;ix.metrics.query_cache_hits=hit+1;reject(()=>R.index(c,r),'index_mutations');ix.metrics.query_cache_hits=hit;const q=ix.queries[0],old=q.node;q.node='!';reject(()=>R.index(c,r),'index_mutations');q.node=old;}
}
for(const c of data.cases){const t=c.timings.indexed,old=t.median_seconds;t.median_seconds+=1;reject(()=>R.validate(data),'timing_mutations');t.median_seconds=old;const hash=t.samples[0].semantic_sha256;t.samples[0].semantic_sha256='!';reject(()=>R.validate(data),'timing_mutations');t.samples[0].semantic_sha256=hash;}
process.stdout.write(JSON.stringify(stats)+'\n');
