from fractions import Fraction as Q
from itertools import combinations,product
from math import gcd,lcm

def sub(a,b):return tuple(x-y for x,y in zip(a,b))
def dot(a,b):return sum(x*y for x,y in zip(a,b))
def cross(a,b):return (a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0])
def plane(a,b,c):
 n=cross(sub(b,a),sub(c,a));d=dot(n,a);v=(*n,d);den=lcm(*(x.denominator for x in v));v=[int(x*den) for x in v];g=gcd(*v);v=tuple(x//g for x in v)
 return v if next(x for x in v if x)>0 else tuple(-x for x in v)
# all wedges inside a unit cube
wedges=[];planes=set()
for axis in range(3):
 tang=[i for i in range(3) if i!=axis]
 for sign in [0,1]:
  corners=[]
  for a,b in product([0,1],repeat=2):
   p=[Q(0)]*3;p[axis]=Q(sign);p[tang[0]]=Q(a);p[tang[1]]=Q(b);corners.append(tuple(p))
  for tri in combinations(corners,3):
   apex=tuple(sum(p[i] for p in tri)/3 if i!=axis else Q(1+sign,3) for i in range(3));tet=(*tri,apex);wedges.append(tet)
   planes.update(plane(*face) for face in combinations(tet,3))

corners=list(product(map(Q,[0,1]),repeat=3))
faces=[[p for p in corners if p[a]==s] for a in range(3) for s in [0,1]]
# order square faces around their center using adjacency
for i,face in enumerate(faces):
 order=[face[0]]
 while len(order)<4:order.append(next(p for p in face if p not in order and sum(x!=y for x,y in zip(p,order[-1]))==1))
 faces[i]=order

def clip(faces,p,sign):
 vals={v:sign*(dot(p[:3],v)-p[3]) for f in faces for v in f}
 if all(d>=0 for d in vals.values()):return faces
 if all(d<=0 for d in vals.values()):return None
 out=[];cut=set()
 for f in faces:
  poly=[]
  for a,b in zip(f,f[1:]+f[:1]):
   da,db=vals[a],vals[b]
   if da>=0:poly.append(a)
   if da*db<0:
    v=tuple((x*db-y*da)/(db-da) for x,y in zip(a,b));poly.append(v);cut.add(v)
   if da==0:cut.add(a)
  if len(poly)>=3:out.append(poly)
 # boundary order by adjacency from clipped faces
 edges=[]
 for f in out:
  for a,b in zip(f,f[1:]+f[:1]):
   if a in cut and b in cut:edges.append((a,b))
 order=[edges[0][0]]
 while len(order)<len(cut):
  nxt=next(b if a==order[-1] else a for a,b in edges if (a==order[-1] and b not in order) or (b==order[-1] and a not in order))
  order.append(nxt)
 out.append(order);return out
atoms=[faces]
for p in sorted(planes):
 atoms=[f for atom in atoms for s in [1,-1] if (f:=clip(atom,p,s)) is not None]
 # identical if not split: clip currently returns None all<= includes allnegative; works


# Store every open arrangement chamber by an exact interior point, its boundary,
# and its exact volume. All coordinates use integer units.
import json
from pathlib import Path
records=[]
for fs in atoms:
 vs={v for f in fs for v in f};center=tuple(sum(v[i] for v in vs)/len(vs) for i in range(3));volume=Q(0);oriented=[]
 for face in fs:
  face=list(face)
  if dot(cross(sub(face[1],face[0]),sub(face[2],face[0])),sub(face[0],center))<0:face.reverse()
  for j in range(1,len(face)-1):volume+=dot(sub(face[0],center),cross(sub(face[j],center),sub(face[j+1],center)))/6
  oriented.append([[int(x*12) for x in v] for v in face])
 assert all((x*240).denominator==1 for x in center)
 assert all((x*12).denominator==1 for v in vs for x in v)
 records.append(dict(point=[int(x*240) for x in center],faces=oriented,volume=[volume.numerator,volume.denominator]))
assert sum(Q(*r['volume']) for r in records)==1
assert len(records)==96
root=Path(__file__).resolve().parents[1]
path=root/'3d-reptiles/chair/tetra-atoms.js'
path.write_text('// Generated by scripts/build-chair-tetra-atoms.py; exact unit-cube arrangement.\nexport const ATOMS = '+json.dumps(records,separators=(',',':'))+';\n')
print('Generated 96 rational chambers; exact total volume 1.')
