#!/usr/bin/env python3
"""Build the browser fixture for the exact ideal icosahedral model-set control."""

from __future__ import annotations

import argparse
import hashlib
import math
from pathlib import Path

from materials_gcts_icosahedral_modelset import (
    HIDDEN_SPECIES_THRESHOLDS,
    HIDDEN_UNIT,
    HIDDEN_WINDOW,
    oracle_patch,
)


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "apps" / "iqc-growth-live" / "ideal-iqc-browser-fixture.js"
SPECIES = {"X": "Al", "Y": "Cu", "Z": "Fe"}
LIFT_BOUND = 3
PHYSICAL_RADIUS = 9.0


def fixture_text() -> str:
    configuration, _hidden_lifts = oracle_patch(LIFT_BOUND, PHYSICAL_RADIUS)
    atoms = sorted(
        ((SPECIES[species], *map(float, position))
         for species, position in zip(configuration.species, configuration.positions)),
        key=lambda atom: (
            round(sum(value * value for value in atom[1:]), 12), atom[0],
            *(round(value, 12) for value in atom[1:])),
    )
    nearest = []
    for index, atom in enumerate(atoms):
        nearest.append(min(math.dist(atom[1:], other[1:])
                           for other_index, other in enumerate(atoms)
                           if index != other_index))
    nearest.sort()
    payload = "\n".join(
        f"{species},{x:.10f},{y:.10f},{z:.10f}"
        for species, x, y, z in atoms
    )
    digest = hashlib.sha256(payload.encode()).hexdigest()
    lines = [
        "// Generated by scripts/build-ideal-iqc-browser-fixture.py; do not edit by hand.",
        "// Exact algorithmic 6D model-set control, not an experimental structure.",
        "export const IDEAL_IQC_BROWSER_FIXTURE = Object.freeze({",
        '  id: "ideal-icosahedral-6d-spherical-window-r9",',
        '  kind: "algorithmic cut-and-project control",',
        '  fixtureClass: "algorithmic",',
        '  materialClaim: "none",',
        '  name: "Exact 6D icosahedral model-set control",',
        '  countLabel: "507 colored physical-space sites",',
        '  license: "repository algorithmic control",',
        '  sourceUrl: "https://github.com/liuyao12/geometric-tree-search/blob/main/scripts/materials_gcts_icosahedral_modelset.py",',
        '  sourceLabel: "generator source",',
        '  provenance: "scripts/materials_gcts_icosahedral_modelset.py::oracle_patch(3, 9.0)",',
        f"  liftBound: {LIFT_BOUND},",
        f"  physicalRadius: {PHYSICAL_RADIUS:.1f},",
        f"  quadraticUnit: {HIDDEN_UNIT:.15f},",
        f"  internalWindowRadius: {HIDDEN_WINDOW:.10f},",
        "  internalSpeciesThresholds: Object.freeze(["
        + ", ".join(f"{value:.10f}" for value in HIDDEN_SPECIES_THRESHOLDS) + "]),",
        f"  rawMinimumDistance: {nearest[0]:.15f},",
        f"  rawMedianNearestDistance: {nearest[len(nearest) // 2]:.15f},",
        f"  atomCount: {len(atoms)},",
        f'  coordinateSpeciesSha256: "{digest}",',
        "  atoms: Object.freeze([",
    ]
    lines.extend(
        f'    Object.freeze(["{species}", {x:.10f}, {y:.10f}, {z:.10f}]),'
        for species, x, y, z in atoms
    )
    lines.extend(["  ]),", "});", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    expected = fixture_text()
    if arguments.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit("ideal IQC browser fixture is stale; rebuild it")
        print("ideal IQC browser fixture: current")
        return
    OUTPUT.write_text(expected)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
