#!/usr/bin/env python3
"""Build the browser replay artifact for the sealed disjoint IQC confirmation.

The artifact contains the original seed and the pre-target-selected first
terminal only.  It deliberately contains no held-out target coordinates.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import zlib
from pathlib import Path

from materials_gcts_iqc_complete_frontier_confirmation_candidates import (
    DEFAULT_FIXTURE,
    EXPECTED_FIXTURE_SHA256,
    EXPECTED_RECEIPT_DIGEST,
    _seed,
    validate_candidate_receipt,
)
from materials_gcts_iqc_complete_frontier_confirmation_preregistration import (
    CONFIRMATION_CENTER,
    EXPECTED_MANIFEST_DIGEST,
    ORACLE_LIFT_BOUND,
    SEED_RADIUS,
    TARGET_RADIUS,
)


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "apps" / "iqc-growth-live" / "iqc-disjoint-confirmation-artifact.js"
FIRST_RESULT = Path(__file__).resolve().parent / "fixtures" / \
    "iqc_complete_frontier_confirmation_result_v1.json"
SECOND_RESULT = Path(__file__).resolve().parent / "fixtures" / \
    "iqc_self_fed_frontier_confirmation_result_v1.json"
FIRST_RESULT_SHA256 = \
    "35abf7d90a05c29ae00c794fd1551b011ec293f04395fc06d32b867a86a81a63"
SECOND_RESULT_SHA256 = \
    "1624c0a3543db2cf14e6aa3ce3e3b8c29bfb442f4e32976be7db898e730dbc2b"
SPECIES = {"X": "Al", "Y": "Cu", "Z": "Fe"}


def _load_json(path: Path, expected_sha256: str):
    raw = path.read_bytes()
    if hashlib.sha256(raw).hexdigest() != expected_sha256:
        raise AssertionError(f"fixture byte drift: {path.name}")
    return json.loads(raw)


def _candidate_receipt():
    raw = Path(DEFAULT_FIXTURE).read_bytes()
    if hashlib.sha256(raw).hexdigest() != EXPECTED_FIXTURE_SHA256:
        raise AssertionError("confirmation candidate fixture byte drift")
    receipt = validate_candidate_receipt(json.loads(raw))
    if receipt["receipt_digest"] != EXPECTED_RECEIPT_DIGEST:
        raise AssertionError("confirmation candidate receipt drift")
    return receipt


def _terminal_actions(receipt):
    raw = zlib.decompress(base64.b64decode(
        receipt["terminal_actions_zlib_base64"], validate=True))
    if hashlib.sha256(raw).hexdigest() != receipt["terminal_actions_sha256"]:
        raise AssertionError("terminal payload drift")
    return json.loads(raw)


def _centered_site(point, color):
    centered = tuple(float(point[axis]) - CONFIRMATION_CENTER[axis]
                     for axis in range(3))
    return (SPECIES[str(color)], *centered)


def _coordinate_digest(sites):
    payload = "\n".join(
        f"{species},{x:.10f},{y:.10f},{z:.10f}"
        for species, x, y, z in sites)
    return hashlib.sha256(payload.encode()).hexdigest()


def artifact_text() -> str:
    receipt = _candidate_receipt()
    first = _load_json(FIRST_RESULT, FIRST_RESULT_SHA256)
    second = _load_json(SECOND_RESULT, SECOND_RESULT_SHA256)
    if (first["protocol_digest"] != EXPECTED_MANIFEST_DIGEST
            or not first["target_domain_disjoint"]
            or not first["candidates_frozen_before_target"]
            or first["target_used_for_fit_candidate_or_ranking"]
            or not first["fusion_top_one_exact"]
            or first["fusion_first_exact_rank"] != 1
            or first["fusion_top_one_correct_sites"] != 3):
        raise AssertionError("first confirmation result is not the sealed green gate")
    if (second["fusion_top_one_exact"]
            or second["six_action_autonomous_gate_passed"]
            or not second["complete_tree_supplies_exact"]
            or second["stationary_or_exponential_claimed"]):
        raise AssertionError("second confirmation result claim boundary drift")

    seed = _seed(ORACLE_LIFT_BOUND)
    if len(seed.positions) != receipt["seed_atoms"]:
        raise AssertionError("regenerated seed count drift")
    seed_sites = sorted(
        (_centered_site(point, color)
         for point, color in zip(seed.positions, seed.species)),
        key=lambda site: (round(sum(value * value for value in site[1:]), 12),
                          site[0], *(round(value, 12) for value in site[1:])),
    )
    terminals = _terminal_actions(receipt)
    selected_index = int(receipt["fusion_order"][0])
    action_sites = sorted(
        (_centered_site(point, color)
         for point, color in terminals[selected_index]),
        key=lambda site: (site[0], *(round(value, 12) for value in site[1:])),
    )
    if len(action_sites) != first["fusion_top_one_correct_sites"]:
        raise AssertionError("selected terminal site count drift")

    all_sites = seed_sites + action_sites
    lines = [
        "// Generated by scripts/build-iqc-disjoint-confirmation-browser-artifact.py; do not edit by hand.",
        "// Contains a seed and a pre-target-selected action; no held-out target coordinates.",
        "export const IQC_DISJOINT_CONFIRMATION_ARTIFACT = Object.freeze({",
        '  id: "iqc-sealed-disjoint-frontier-confirmation-v1",',
        '  kind: "sealed spatially disjoint continuation confirmation",',
        '  fixtureClass: "algorithmic confirmation",',
        '  materialClaim: "exact 6D spherical-window model-set control",',
        f'  protocolDigest: "{first["protocol_digest"]}",',
        f'  candidateReceiptDigest: "{receipt["receipt_digest"]}",',
        f'  candidateFixtureSha256: "{EXPECTED_FIXTURE_SHA256}",',
        f'  candidateSetDigest: "{receipt["candidate_digest"]}",',
        f'  executionDigest: "{receipt["execution_digest"]}",',
        f'  firstResultSha256: "{FIRST_RESULT_SHA256}",',
        f'  secondResultSha256: "{SECOND_RESULT_SHA256}",',
        f"  sourceCenter: Object.freeze([{', '.join(f'{v:.1f}' for v in CONFIRMATION_CENTER)}]),",
        f"  seedRadius: {SEED_RADIUS:.10f},",
        f"  firstTargetRadius: {TARGET_RADIUS:.10f},",
        f"  seedAtomCount: {len(seed_sites)},",
        f"  terminalCount: {first['terminal_count']},",
        f"  exactTerminalCountPosthoc: {first['exact_terminal_count']},",
        f"  selectedTerminalIndex: {selected_index},",
        f"  selectedTerminalSiteCount: {len(action_sites)},",
        f"  targetAtomCountPosthoc: {first['target_atoms']},",
        f"  novelTargetAtomCountPosthoc: {first['novel_target_atoms']},",
        "  candidatesFrozenBeforeTarget: true,",
        "  targetUsedForFitCandidateOrRanking: false,",
        "  targetOpenCount: 1,",
        "  targetDomainDisjoint: true,",
        "  firstFusionTopOneExact: true,",
        "  stationaryOrExponentialClaimed: false,",
        f'  coordinateSpeciesSha256: "{_coordinate_digest(all_sites)}",',
        "  secondBlock: Object.freeze({",
        f"    terminalCount: {second['terminal_count']},",
        f"    exactTerminalCountPosthoc: {second['exact_terminal_count']},",
        f"    scalarFirstExactRank: {second['scalar_first_exact_rank']},",
        f"    fusionFirstExactRank: {second['fusion_first_exact_rank']},",
        "    fusionTopOneExact: false,",
        "    portfolioSuppliesExact: false,",
        "    completeTreeSuppliesExact: true,",
        "    sixActionAutonomousGatePassed: false,",
        "    stationaryOrExponentialClaimed: false,",
        '    honestStatus: "second complete frontier is available, but frozen autonomous selection is red",',
        "  }),",
        "  seedSites: Object.freeze([",
    ]
    lines.extend(
        f'    Object.freeze(["{species}", {x:.10f}, {y:.10f}, {z:.10f}]),'
        for species, x, y, z in seed_sites)
    lines.extend(["  ]),", "  selectedActionSites: Object.freeze(["])
    lines.extend(
        f'    Object.freeze(["{species}", {x:.10f}, {y:.10f}, {z:.10f}]),'
        for species, x, y, z in action_sites)
    lines.extend(["  ]),", "});", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = artifact_text()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit("IQC disjoint confirmation browser artifact is stale")
        print("IQC disjoint confirmation browser artifact: current")
        return
    OUTPUT.write_text(expected)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
