"""Export independently checked geometric research without reclassifying weighted tiles."""
import argparse, json, pathlib, hashlib
p = argparse.ArgumentParser()
p.add_argument('--runs', required=True)
p.add_argument('--output', required=True)
a = p.parse_args()
root = pathlib.Path(a.runs)
choices = [
 ('a2sa-size10-unbalanced-reflections-next64-20260906', 'a2sa_10_76076', '24-copy periodic parent', 'reflection-periodic24.ndjson', 'independent-reflection-period24.ndjson'),
 ('a2pair20-from76076-20260906', 'a2pair_20_4c8015f2f0fc', '24-copy periodic chain cluster', 'reflection-periodic24-chain.ndjson', 'independent-reflection-period24-chain.ndjson'),
 ('a2sa-size10-unbalanced-reflections-next32-20260906', 'a2sa_10_65558', 'Deep geometric non-tiler', None, None),
]
def lines(path):
 return [json.loads(s) for s in path.read_text().splitlines() if s.strip()]
out = []
for folder, ident, label, certificate, replay in choices:
 d = root / folder
 source = next(r for r in lines(d/'input.ndjson') if r['id'] == ident)
 evidence = {'scope': 'Exact Kuhn-alcove unions; integer translations; full 12-element A2 group, including reflections. Not the weighted lattice-function model.', 'input_sha256': hashlib.sha256((d/'input.ndjson').read_bytes()).hexdigest()}
 if certificate:
  cert = next(r for r in lines(d/certificate) if r['id']==ident)
  checked = next(r for r in lines(d/replay) if r['id']==ident)
  assert checked['verified'] and checked['copies']==24
  evidence.update(classification='periodic', certificate=cert, independent_replay=checked)
  note = 'Independently verified 24-copy periodic quotient. This is a found domain, not a proven minimum. Retained as a larger-domain discovery control, not an aperiodic candidate.'
 else:
  summary=json.loads((d/'verified-classification-final.json').read_text())
  rec=next(r for r in summary['records'] if r['id']==ident)
  assert rec['classification']=='geometric_non_tiler'
  evidence.update(classification='geometric_non_tiler', evidence=rec['evidence'])
  note='Survives a nine-face-step geometric neighborhood (213 added tiles), but an independently checked finite obstruction rules out this geometric model. Retained as a delayed-failure benchmark, not an aperiodic candidate.'
 out.append(dict(id=ident, registry_id='research_'+ident, name=label+' · '+ident, kind='a2_geometric_research', alcoves=source['alcoves'], screening={'status':'other_model_research'}, research_review={'note':note+' The interactive six lanes below still solve weighted lattice functions; their outcomes must not be confused with these exact geometric results.', **evidence}))
reviews={}
for d in sorted(root.glob('a2*20260906')):
 for f in d.glob('verified-classification*.json'):
  s=json.loads(f.read_text())
  if s.get('scope')!='exact_Kuhn_alcove_geometry_full_A2_group_not_weighted_model': continue
  if hashlib.sha256((d/'input.ndjson').read_bytes()).hexdigest()!=s['input_sha256']: raise ValueError(f)
  for r in s['records']:
   if r['classification']=='unresolved': continue
   old=reviews.get(r['id'])
   if old and old['classification']!=r['classification']: raise ValueError(r['id'])
   reviews[r['id']]={**r, 'source':str(f.relative_to(root))}
result={'date':'2026-09-06', 'criteria':{'periodic':'Retain found motifs of at least five copies as controls; never imply minimum period without an exclusion proof.', 'non_tiler':'Retain delayed finite obstructions as regression benchmarks.', 'unresolved':'Bounded searches only; neither long survival nor a cutoff establishes aperiodicity.', 'scope':'Track geometry, allowed symmetry group, and weighted lattice functions separately.'}, 'candidates':out, 'previous_geometric_reviews':reviews}
pathlib.Path(a.output).write_text('// Generated by scripts/build-interesting-tile-review.py.\nexport const INTERESTING_TILE_REVIEW = '+json.dumps(result,indent=2)+';\n')
