#!/usr/bin/env python3
"""Target-blind runtime for the frozen IQC terminal-fusion policy.

Candidate geometry is generated by the already-selected three-action
pose/port portfolio.  A local irregular-support section and its complete
connection/failure incidence graph are then evaluated by a frozen scalar plus
equivariant rank fusion.  This module has no target or scorer API.
"""

from __future__ import annotations

import bz2
import hashlib
import json
import math
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace

from materials_gcts_equivariant_port_fusion_value import (
    EquivariantPortFusionCandidate, select_equivariant_port_fusion)
from materials_gcts_frontier_attachment_benchmark import (
    _dominant_source_color)
from materials_gcts_iqc_frozen_fusion_artifact import runtime_from_payload
from materials_gcts_iqc_incidence_token_preflight import _key
from materials_gcts_iqc_pose_port_state_audit import _descriptors
from materials_gcts_iqc_recurrent_branch_autonomous_confirmation import (
    UPSTREAM_ANGULAR_BIN_WIDTH)
from materials_gcts_iqc_recurrent_prototype_connection_audit import _bounded
from materials_gcts_iqc_spatial_beam_transfer_benchmark import CLUSTER_EDGES
from materials_gcts_icosahedral_modelset import HIDDEN_UNIT
from materials_gcts_local_section_tensor import (
    LocalSectionSchema, local_section_feature_names, local_section_tensor)
from materials_gcts_partial_irregular_port_graph import (
    partial_irregular_port_graph)
from materials_gcts_partial_irregular_section import partial_irregular_section
from materials_gcts_persistent_frontier_beam import (
    advance_frontier_configuration)
from materials_gcts_pose_port_state_marking import (
    pose_port_state_code, score_pose_port_state)
from materials_gcts_recurrent_state_diverse_beam import (
    RecurrentStateBeamCandidate, RecurrentStateBeamSpec,
    select_recurrent_state_diverse_beam)
from materials_gcts_recursive_connections import local_cluster_types


COLORS = ("X", "Y", "Z")
SCHEDULE = (4, 4, 8)
BEAM_SPECS = (
    RecurrentStateBeamSpec(4., 1, 4),
    RecurrentStateBeamSpec(4., 2, 4),
    RecurrentStateBeamSpec(2., 1, 8),
)
PAIR_KEYS = (("X", "X"), ("X", "Y"), ("X", "Z"),
             ("Y", "Y"), ("Y", "Z"), ("Z", "Z"))
BASE_NAMES = (
    "depth", "sum_log_state_probability", "minimum_state_probability",
    "sum_state_probability", "sum_state_votes", "maximum_state_votes",
    "emitted_species_count", "minimum_action_separation",
    "mean_action_separation", "maximum_action_separation",
)
BRANCH_NAMES = BASE_NAMES + tuple(
    "colored_separation:" + "".join(pair) for pair in PAIR_KEYS
) + tuple(f"pose_port_channel:{slot}:{channel}"
          for slot in range(3) for channel in range(5))
BRANCH_VARIANTS = {
    "base": tuple(range(10)),
    "colored": tuple(range(16)),
    "ports": tuple(range(10)) + tuple(range(16, 31)),
    "coupled": tuple(range(31)),
}
SECTION_SCHEMA = LocalSectionSchema(
    COLORS, HIDDEN_UNIT, radial_bin_width=.5, radial_bins=8,
    angular_cutoff=3., angular_bins=6, include_chirality=False)
SECTION_NAMES = local_section_feature_names(SECTION_SCHEMA)
PARTIAL_NAMES = (
    "partial-min-fraction", "partial-mean-fraction",
    "partial-min-atoms", "partial-mean-atoms", "partial-min-group-support",
)
INCIDENCE_NAMES = (
    "partial-pair-min-shared-occupied",
    "partial-pair-mean-shared-occupied",
    "partial-pair-max-shared-occupied",
    "partial-connected-action-pairs",
)
FEATURE_NAMES = BRANCH_NAMES + SECTION_NAMES + PARTIAL_NAMES + INCIDENCE_NAMES
DEFAULT_FIXTURE = Path(__file__).resolve().parent / \
    "fixtures/iqc_frozen_terminal_fusion_v1.json.bz2"
EXPECTED_FIXTURE_SHA256 = \
    "6ab3b23317207577a2805a27f3fa399d312e9c2eefa7d9c858731bd9a456f6d5"
EXPECTED_ARTIFACT_DIGEST = \
    "fbdbdf307227921ad24d11b81aea31e9835acf50ae2359d0807cc184b96c623c"
EXPECTED_FUSION_MODEL_DIGEST = \
    "505b65481e3fe2cc25a284ba8dc175e3a794465c2c7bd726f5448c1fac6bbef5"


@dataclass(frozen=True)
class FusionSearchState:
    positions: tuple
    species: tuple
    proposals: object
    actions: tuple
    probabilities: tuple
    votes: tuple
    cumulative: float
    channel_marks: tuple


@dataclass(frozen=True)
class FrozenFusionTerminal:
    actions: tuple[tuple[tuple[float, float, float], str], ...]
    scalar_features: tuple[float, ...]
    action_colors: tuple[str, ...]
    graph: object
    tie_key: tuple


@dataclass(frozen=True)
class FrozenFusionNucleus:
    center: tuple[float, float, float]
    seed_atoms: int
    candidate_counts_by_depth: tuple[int, ...]
    retained_counts_by_depth: tuple[int, ...]
    terminal_count: int
    candidate_digest: str
    scalar_stable_index: int
    fusion_stable_index: int
    scalar_order: tuple[int, ...]
    fusion_order: tuple[int, ...]
    terminals: tuple[FrozenFusionTerminal, ...]
    target_used: bool = False


def action_key(actions):
    return tuple(sorted(actions))


def _color_population(actions):
    return tuple((color, sum(value == color for _point, value in actions))
                 for color in sorted({value for _point, value in actions}))


def branch_features(state: FusionSearchState):
    distances = tuple(math.dist(first[0], second[0])
                      for index, first in enumerate(state.actions)
                      for second in state.actions[index + 1:])
    colored = {pair: [] for pair in PAIR_KEYS}
    for index, (point, color) in enumerate(state.actions):
        for other, other_color in state.actions[index + 1:]:
            colored[tuple(sorted((color, other_color)))].append(
                math.dist(point, other))
    base = (
        float(len(state.actions)), state.cumulative,
        min(state.probabilities), sum(state.probabilities),
        float(sum(state.votes)), float(max(state.votes)),
        float(len({color for _point, color in state.actions})),
        min(distances) if distances else 0.,
        sum(distances) / len(distances) if distances else 0.,
        max(distances) if distances else 0.,
    )
    pairs = tuple(sum(colored[pair]) / len(colored[pair])
                  if colored[pair] else 0. for pair in PAIR_KEYS)
    marks = tuple(sorted(state.channel_marks))
    channels = tuple(float(value) for slot in range(3) for value in (
        marks[slot][1] if slot < len(marks) else (0, 0, 0, 0, 0)))
    return base + pairs + channels


def _child(source, connection, state_model, state, point, descriptor,
           target_radius, geometry_cache=None):
    color = str(_dominant_source_color(state.proposals, point))
    probability = score_pose_port_state(state_model, descriptor)
    vote = int(state.proposals.votes[point])
    code = pose_port_state_code(
        state_model.token_marking, descriptor,
        state_bin_width=state_model.state_bin_width,
        channel_families=state_model.channel_families)
    geometry_key = action_key(
        state.actions + ((tuple(point), color),))
    geometry = None if geometry_cache is None else geometry_cache.get(
        geometry_key)
    if geometry is None:
        geometry = advance_frontier_configuration(
            connection, state.proposals, state.positions, state.species,
            (point,), (color,), CLUSTER_EDGES, source.group, target_radius)
        if geometry_cache is not None:
            geometry_cache[geometry_key] = geometry
    positions, species, future = geometry
    return FusionSearchState(
        positions, species, future,
        state.actions + ((tuple(point), color),),
        state.probabilities + (probability,), state.votes + (vote,),
        state.cumulative + math.log(max(probability, 1e-15)),
        state.channel_marks + ((color, tuple(code)),))


def _portfolio_select(models, depth, states, spec):
    ranked_by_variant = []
    for name, indices in BRANCH_VARIANTS.items():
        head = models[name][depth]
        rows = tuple(RecurrentStateBeamCandidate(
            tuple(branch_features(state)[index] for index in indices),
            tuple(color for _point, color in state.actions),
            action_key(state.actions), state) for state in states)
        ranked_by_variant.append(
            select_recurrent_state_diverse_beam(head, rows, spec))
    selected, seen, rank = [], set(), 0
    while len(selected) < spec.beam_width:
        changed = False
        for rows in ranked_by_variant:
            if rank < len(rows) and rows[rank].tie_key not in seen:
                selected.append(rows[rank].payload)
                seen.add(rows[rank].tie_key)
                changed = True
                if len(selected) >= spec.beam_width:
                    break
        if not changed and all(rank >= len(rows) - 1
                               for rows in ranked_by_variant):
            break
        rank += 1
    return tuple(selected)


def _terminal_states(source, connection, state_model, branch_models,
                     target_radius):
    frontier = _bounded(connection, source, local_cluster_types(
        source.seed_positions, source.seed_species, CLUSTER_EDGES))
    states = (FusionSearchState(
        tuple(source.seed_positions), tuple(source.seed_species), frontier,
        (), (), (), 0., ()),)
    counts, retained = [], []
    for depth, (reach, spec) in enumerate(zip(SCHEDULE, BEAM_SPECS)):
        children = {}
        for state in states:
            descriptors = _descriptors(
                state.positions, state.species, state.proposals,
                UPSTREAM_ANGULAR_BIN_WIDTH)
            ordered = tuple(sorted(state.proposals.votes, key=lambda point: (
                -score_pose_port_state(state_model, descriptors[point]),
                -state.proposals.votes[point], point)))[:reach]
            for point in ordered:
                candidate = _child(
                    source, connection, state_model, state, point,
                    descriptors[point], target_radius)
                key = action_key(candidate.actions)
                prior = children.get(key)
                if prior is None or (candidate.cumulative, candidate.actions) > \
                        (prior.cumulative, prior.actions):
                    children[key] = candidate
        stage = tuple(sorted(children.values(),
                             key=lambda row: action_key(row.actions)))
        counts.append(len(stage))
        states = _portfolio_select(branch_models, depth, stage, spec)
        retained.append(len(states))
    return states, tuple(counts), tuple(retained)


def _local_section(state):
    action_keys = {_key(point) for point, _color in state.actions}
    occupied = tuple((point, str(color)) for point, color in
                     zip(state.positions, state.species)
                     if _key(point) not in action_keys)
    return local_section_tensor(
        tuple(point for point, _color in state.actions),
        tuple(color for _point, color in state.actions),
        tuple(point for point, _color in occupied),
        tuple(color for _point, color in occupied), SECTION_SCHEMA).values


def _partial_section(source, state, grouped):
    row = partial_irregular_section(
        grouped.vocabulary, grouped.training_group_support,
        source.seed_positions, source.seed_species,
        tuple(point for point, _color in state.actions),
        tuple(color for _point, color in state.actions))
    graph = partial_irregular_port_graph(
        row, source.seed_positions, source.seed_species,
        tuple(point for point, _color in state.actions),
        tuple(color for _point, color in state.actions),
        distance_scale=HIDDEN_UNIT, distance_bin_width=.25)
    return row, graph


def _partial(source, state, grouped):
    row, graph = _partial_section(source, state, grouped)
    values = (
        row.minimum_matched_fraction, row.mean_matched_fraction,
        float(row.minimum_matched_atoms),
        sum(match.matched_atoms for match in row.action_matches) /
        len(row.action_matches),
        float(min(match.training_group_support
                  for match in row.action_matches)),
        float(row.minimum_pair_shared_occupied),
        row.mean_pair_shared_occupied,
        float(row.maximum_pair_shared_occupied),
        float(row.connected_action_pairs),
    )
    return values, graph


def freeze_nucleus(runtime, *, center, seed_positions, seed_species,
                   target_radius):
    source = SimpleNamespace(
        group=tuple(map(float, center)),
        seed_positions=tuple(tuple(map(float, point))
                             for point in seed_positions),
        seed_species=tuple(map(str, seed_species)))
    states, counts, retained = _terminal_states(
        source, runtime["connection"], runtime["state_model"],
        runtime["branch_models"], target_radius)
    terminals = []
    for state in states:
        partial, graph = _partial(
            source, state, runtime["grouped_vocabulary"])
        features = tuple(branch_features(state)) + _local_section(state) + partial
        colors = tuple(color for _point, color in state.actions)
        terminals.append(FrozenFusionTerminal(
            action_key(state.actions), features, colors, graph,
            action_key(state.actions)))
    terminals = tuple(sorted(terminals, key=lambda row: repr(row.tie_key)))
    if not terminals:
        raise AssertionError("frozen fusion runtime produced no terminal")
    candidates = tuple(EquivariantPortFusionCandidate(
        row.scalar_features, row.action_colors, row.graph, row.tie_key)
        for row in terminals)
    fusion = select_equivariant_port_fusion(
        runtime["fusion_model"], candidates)
    scalar_model = _scalar_only_model(
        runtime["fusion_model"])
    scalar = select_equivariant_port_fusion(scalar_model, candidates)
    scalar_order = tuple(sorted(range(len(terminals)), key=lambda index: (
        -scalar.fused_scores[index], repr(terminals[index].tie_key))))
    fusion_order = tuple(sorted(range(len(terminals)), key=lambda index: (
        -fusion.fused_scores[index], repr(terminals[index].tie_key))))
    digest = hashlib.sha256(repr(tuple(
        (row.actions, row.scalar_features, row.action_colors,
         row.graph.canonical_digest) for row in terminals)).encode()).hexdigest()
    return FrozenFusionNucleus(
        tuple(map(float, center)), len(source.seed_positions), counts, retained,
        len(terminals), digest, scalar.stable_index, fusion.stable_index,
        scalar_order, fusion_order, terminals)


def _scalar_only_model(model):
    """Return the identical frozen model with graph rank weight zero."""
    return type(model)(
        model.scalar, model.graph, 0., model.feature_names, model.color_keys,
        model.training_groups, model.model_digest, model.target_used)


def load_runtime(path: Path, *, compressed_sha256: str,
                 artifact_digest: str, fusion_model_digest: str):
    compressed = path.read_bytes()
    if hashlib.sha256(compressed).hexdigest() != compressed_sha256:
        raise AssertionError("frozen fusion fixture byte digest drift")
    payload = json.loads(bz2.decompress(compressed))
    runtime = runtime_from_payload(payload)
    if runtime["artifact_digest"] != artifact_digest:
        raise AssertionError("frozen fusion artifact digest drift")
    if runtime["fusion_model"].model_digest != fusion_model_digest:
        raise AssertionError("frozen fusion model digest drift")
    if (tuple(runtime["fusion_model"].feature_names) != FEATURE_NAMES
            or set(runtime["branch_models"]) != set(BRANCH_VARIANTS)
            or any(len(heads) != len(SCHEDULE)
                   for heads in runtime["branch_models"].values())):
        raise AssertionError("frozen fusion runtime schema drift")
    return runtime


def load_default_runtime():
    return load_runtime(
        DEFAULT_FIXTURE, compressed_sha256=EXPECTED_FIXTURE_SHA256,
        artifact_digest=EXPECTED_ARTIFACT_DIGEST,
        fusion_model_digest=EXPECTED_FUSION_MODEL_DIGEST)
