import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const app = readFileSync(new URL("../apps/iqc-growth-live/app.js", import.meta.url), "utf8");
const document = readFileSync(new URL("../apps/iqc-growth-live/index.html", import.meta.url), "utf8");
const styles = readFileSync(new URL("../apps/iqc-growth-live/style.css", import.meta.url), "utf8");
const readme = readFileSync(new URL("../apps/iqc-growth-live/README.md", import.meta.url), "utf8");
const benchmark = readFileSync(new URL("../docs/projects/materials-recursive-gcts-benchmark.md", import.meta.url), "utf8");
const atlas = readFileSync(new URL("../apps/iqc-growth-live/evidence-atlas.js", import.meta.url), "utf8");
const library = readFileSync(new URL("../apps/iqc-growth-live/public-powder-profile-library.mjs", import.meta.url), "utf8");
const formFactors = readFileSync(new URL("../apps/iqc-growth-live/xray-form-factors.mjs", import.meta.url), "utf8");
const libraryData = JSON.parse(readFileSync(new URL("../apps/iqc-growth-live/data/rruff-powder-profiles-v1.json", import.meta.url), "utf8"));

assert.match(app, /experimental-scattering-validation\.mjs\?v=20260901-428/);
assert.match(app, /public-powder-profile-library\.mjs\?v=20260901-428/);
assert.match(app, /xray-form-factors\.mjs\?v=20260901-428/);
assert.match(app, /experimentalPowderProfileValidation/);
assert.match(app, /candidateSetChanged: false/);
assert.match(app, /runExperimentalScatteringDemonstrator/);
assert.match(app, /qDependentAtomicFormFactorsUsed: displayedScatteringContrastMode === "xray"/);
assert.match(app, /formFactorSourceSha256/);
assert.match(app, /periodicBraggXrayPowderIntensity/);
assert.match(app, /periodicTranslationalCoherenceUsed/);
assert.match(app, /occupancyWeightedScatteringUsed/);
assert.match(app, /coherent-average-site-amplitude/);
assert.match(app, /experimentalScatteringCoherence\.addEventListener/);
assert.match(app, /full reported Cartesian Uiso\/Uij reduced to intrinsic-dimensional Ueq/);
assert.match(document, /Independent powder-profile validation/);
assert.match(document, /download pdCIF request/);
assert.match(document, /run instrument demonstrator/);
assert.match(document, /browse public RRUFF profiles/);
assert.match(document, /chemistry alone never establishes phase identity/);
assert.match(document, /model coherence/);
assert.match(document, /periodic cell · 20 nm/);
assert.match(styles, /experimental-scattering-card/);
assert.match(styles, /public-powder-profile-panel/);
assert.match(styles, /profile-residual/);
assert.match(styles, /profile-uncertainty/);
assert.match(readme, /Build 417/);
assert.match(readme, /Build 419/);
assert.match(readme, /Build 420/);
assert.match(readme, /Build 421/);
assert.match(readme, /demonstratorOnly/);
assert.match(benchmark, /Independent powder-profile validation boundary/);
assert.match(atlas, /Experiment-facing powder validation/);
assert.match(atlas, /q-dependent X-ray amplitudes/);
assert.match(library, /sameMaterialClaimAllowed/);
assert.match(library, /q-dependent X-ray f0 channel/);
assert.match(formFactors, /Cromer-Mann/);
assert.match(formFactors, /d6ccb33d4be318adfd8a73ae30ce3a01ed0c5a8d/);
assert.match(formFactors, /qDependentFormFactorsUsed: true/);
assert.match(formFactors, /Gaussian reciprocal-domain envelope/);
assert.match(formFactors, /coherent average-site amplitude/);
assert.equal(libraryData.schema, "gcts-rruff-powder-profile-library-v1");
assert.equal(libraryData.profileCount, 15);
assert.equal(libraryData.profiles.filter(profile => profile.phase === "Halite").length, 3);
assert.equal(new Set(libraryData.profiles.map(profile => profile.rruffId)).size, 15);

console.log("experimental scattering portal contract: all tests passed");
