import {buildAtlas,penroseArrows,inspectPatch} from './atlas-engine.js?v=20261002';

const $=id=>document.getElementById(id);
const sources={
  grid:['Multigrid construction','https://drops.dagstuhl.de/entities/document/10.4230/OASIcs.AUTOMATA.2021.9'],
  root:['Root-lattice construction','https://www.gregegan.net/APPLETS/12/deBruijnNotes.html#An'],
  ttt:['Tübingen triangle reference','https://tilings.math.uni-bielefeld.de/substitution/tuebingen-triangle/'],
  p3:['Penrose rhomb reference','https://tilings.math.uni-bielefeld.de/substitution/penrose-rhomb/'],
  socolar:['Socolar’s matching rules','https://doi.org/10.1007/BF02097107'],
  cast:['Cyclotomic substitution theory','https://arxiv.org/abs/1606.06858'],
  ab:['Octagonal cut-and-project construction','https://arxiv.org/html/2308.07701v2'],
  p1:['Original finite reference patch','https://commons.wikimedia.org/wiki/File:Penrose_Tiling_(P1).svg']
};
const catalog=[
  {id:'p3',name:'Penrose rhombs',short:'Two unit-edge rhombs',group:'Pentagonal field',n:5,m:5,shapes:'2',inflation:'\\varphi=(1+\\sqrt5)/2',
    description:'The thin and thick Penrose rhombs. A regular pentagrid selects this patch; the optional single and double arrows are solved consistently across its shared edges.',
    relation:'Keep the phase fixed and switch to kite-and-dart or Robinson triangles to see local recuttings of this same patch. Their displayed tile sizes differ because the boundaries change.',links:['p3','grid'],search:['Explore Penrose matching','./']},
  {id:'p2',name:'Kite & dart',short:'Penrose P2 · local recutting',group:'Pentagonal field',n:5,m:5,shapes:'2',inflation:'\\varphi',
    description:'The convex kite and concave dart, reconstructed from the marked Penrose rhombs. Complete faces are retained; a narrow fringe is lost at the finite patch boundary.',
    relation:'Same underlying Penrose pattern, different tile boundaries. Turn on Source rhombs to compare both presentations directly. Kite and dart edges have two lengths in the golden ratio.',links:['p3'],search:['Explore kite-and-dart matching','./']},
  {id:'robinson',name:'Robinson triangles',short:'Penrose · split the rhombs',group:'Pentagonal field',n:5,m:5,shapes:'2',inflation:'\\varphi',
    description:'Each thick rhomb is cut along its long diagonal and each thin rhomb along its short diagonal. The result has acute and obtuse golden triangles.',
    relation:'This is a subdivision of the Penrose patch. It is different from the Tübingen tiling below, even though both use the same two triangle shapes up to scale.',links:['p3','ttt']},
  {id:'p1',name:'Pentagons, boats & stars',short:'Penrose P1 · finite reference',group:'Pentagonal field',n:5,m:5,shapes:'4 outlines · 6 classes',inflation:null,
    description:'The original Penrose family: pentagons, stars, boats, and diamonds. The three pentagon colors distinguish the reference’s tile classes; their full matching decorations are not drawn.',
    relation:'A finite published patch, reconstructed in exact cyclotomic coordinates. Reveal, pan, zoom, and inspect it; section motion and patch enlargement apply to the generated examples instead.',links:['p1'],search:['Explore P1 matching','./']},
  {id:'ttt',name:'Tübingen triangles',short:'A distinct pentagonal structure',group:'Pentagonal field',n:5,m:5,shapes:'2 outlines',inflation:'\\varphi',
    description:'Project the triangular Delaunay faces selected by a section of the root lattice \\(A_4\\). The two triangle outlines have golden-ratio side lengths. This view colors outlines, not the four handed substitution types.',
    relation:'The same number field as Penrose, but a different structure. Penrose is locally derivable from Tübingen; the reverse local reconstruction is not possible in general.',links:['ttt','root']},
  {id:'ab',name:'Ammann–Beenker',short:'Square + silver rhomb',group:'Other cyclotomic fields',n:8,m:4,shapes:'2',inflation:'1+\\sqrt2',
    description:'The octagonal square-and-rhomb tiling, generated by a four-grid section. All edges have the same length; the smaller rhomb angle is \\(\\pi/4\\).',
    relation:'This gallery uses the cut-and-project construction. The octagonal search page instead grows finite patches using the published edge arrows and vertex-house matching rule.',links:['ab','grid'],search:['Explore octagonal matching','./ammann-beenker.html']},
  {id:'seven',name:'Sevenfold rhombs',short:'Three equal-side shapes',group:'Other cyclotomic fields',n:7,m:7,shapes:'3',inflation:null,
    description:'A regular seven-grid produces the three unit-edge rhombs with smaller angles \\(\\pi/7\\), \\(2\\pi/7\\), and \\(3\\pi/7\\). Phase motion reveals local rearrangements within this construction.',
    relation:'These canonical projection patches belong to the setting of Socolar’s alternation rules. His marked tiling family also admits bounded departures from canonical projection. The arrows are explored on the search page.',links:['grid','socolar'],search:['Explore Socolar arrows','./?ring=7']},
  {id:'tri7',name:'Sevenfold triangles',short:'Root-lattice relative of Tübingen',group:'Other cyclotomic fields',n:7,m:7,shapes:'4',inflation:null,
    description:'The analogous root-lattice construction in \\(A_6\\) gives four triangle outlines in \\(\\mathbb Q(\\zeta_7)\\). Their edges are differences of roots of unity, with several lengths.',
    relation:'Compare with the sevenfold rhombs: the ambient field is shared, while the selected higher-dimensional cells and the resulting tiles differ. No local equivalence or matching-rule identity is asserted.',links:['root','cast']},
  {id:'twelve',name:'Dodecagonal rhombs',short:'Three shapes · six directions',group:'Other cyclotomic fields',n:12,m:6,shapes:'3',inflation:null,
    description:'Six grid families give unit-edge rhombs with smaller angles \\(\\pi/6\\), \\(\\pi/3\\), and \\(\\pi/2\\). The last shape is a square.',
    relation:'A dodecagonal multigrid family. This is not labeled as the Socolar square–hexagon–rhomb tile set, and the gallery does not supply a universal edge marking for it.',links:['grid','cast']},
  {id:'eleven',name:'Elevenfold rhombs',short:'Five equal-side shapes',group:'Other cyclotomic fields',n:11,m:11,shapes:'5',inflation:null,
    description:'Eleven grid directions yield five unit-edge rhomb shapes, with smaller angles \\(k\\pi/11\\) for \\(1\\leq k\\leq5\\). This is the same multigrid construction at a higher cyclotomic degree.',
    relation:'Socolar’s odd-prime construction applies in this setting, but those larger arrow catalogs are not implemented in this viewer. The second embedding displays only one plane of the internal coordinates.',links:['grid','socolar']}
];
const palette=['#83bca8','#e4b76b','#a7a8d4','#d5907f','#7eabc6','#bbbf83'];
const preferred={'rhomb-1':1,'rhomb-2':0,'rhomb-3':2,'rhomb-4':3,'rhomb-5':4,kite:0,dart:2,acute:0,obtuse:1,p5:0,p3:2,p2:3,diamond:1,boat:4,star:5,'triangle-1-2-2':0,'triangle-1-1-3':1,'triangle-2-2-3':0,'triangle-1-2-4':2,'triangle-1-1-5':1,'triangle-1-3-3':3};
const color=kind=>palette[preferred[kind]??0];
const initial=new URL(location.href).searchParams.get('tiling');
let entry=catalog.find(c=>c.id===initial)||catalog[0],model=null,arrows=null,reveal=0,phase=0,radius=12,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches;
let selected=null,hover=null,filter=null,gained=new Set(),generation=0,phaseDirection=1,phaseTick=0,buildTimer;
let width=900,height=500,dpr=1,scale=20,pan=[0,0],zoom=1,drag=null,dirty=true;
const canvas=$('tiling'),ctx=canvas.getContext('2d'),internal=$('internal'),ic=internal.getContext('2d');
let mathQueue=Promise.resolve();
function math(elements){mathQueue=mathQueue.catch(()=>{}).then(async()=>{if(window.MathJax?.startup?.promise){await MathJax.startup.promise;MathJax.typesetClear(elements);await MathJax.typesetPromise(elements);}});}
window.addEventListener('load',()=>math([$('library'),$('facts'),$('description'),$('relation'),$('legend'),$('internalCaption')]));
function frac(k,m){return k===m/2?'\\pi/2':`${k===1?'':k}\\pi/${m}`;}
function shapeName(t){
  if(t.kind.startsWith('rhomb-'))return t.angle===model.m/2?'Square':`Rhomb \\(${frac(t.angle,model.m)}\\)`;
  if(t.angles)return `Triangle \\((${t.angles.map(k=>frac(k,model.m)).join(',\\,')})\\)`;
  return ({kite:'Kite',dart:'Dart',acute:'Acute golden triangle',obtuse:'Obtuse golden triangle',p5:'Pentagon · class 5',p3:'Pentagon · class 3',p2:'Pentagon · class 2',diamond:'Diamond',boat:'Boat',star:'Star'})[t.kind]||t.kind;
}
function polynomial(c,n){let out='';c.forEach((v,i)=>{if(!v)return;const a=Math.abs(v);out+=(out?(v<0?' - ':' + '):(v<0?'-':''))+(i?(a===1?'':a)+(i===1?`\\zeta_{${n}}`:`\\zeta_{${n}}^{${i}}`):a);});return out||'0';}
function makeLibrary(){let group='';for(const item of catalog){if(item.group!==group){group=item.group;const label=document.createElement('div');label.className='group-label';label.textContent=group;$('library').append(label);}
  const button=document.createElement('button');button.className='tile-card';button.dataset.tiling=item.id;button.setAttribute('aria-pressed',String(item===entry));button.innerHTML=`<canvas width="98" height="88" aria-hidden="true"></canvas><span><strong>${item.name}</strong><small>${item.short}</small></span>`;button.addEventListener('click',()=>choose(item));$('library').append(button);
  const mini=buildAtlas(item.id,{radius:3.5}),mc=button.querySelector('canvas').getContext('2d');
  mc.translate(49,44);mc.scale(10,-10);for(const t of mini.tiles){if(t.center[0]**2+t.center[1]**2>10)continue;mc.beginPath();t.points.forEach((p,i)=>i?mc.lineTo(...p):mc.moveTo(...p));mc.closePath();mc.fillStyle=color(t.kind);mc.fill();mc.strokeStyle='#496659';mc.lineWidth=.06;mc.stroke();}
}}
function info(){
  $('family').textContent=entry.group;$('name').textContent=entry.name;$('description').innerHTML=entry.description;$('relation').innerHTML=entry.relation;
  $('facts').innerHTML=`<div class="fact"><span>Coordinates</span><strong>\\(\\mathbb Z[\\zeta_{${entry.n}}]\\)</strong></div><div class="fact"><span>Field degree</span><strong>\\(${model.r.degree}\\)</strong></div><div class="fact"><span>Tile shapes</span><strong>${entry.shapes}</strong></div><div class="fact"><span>${entry.inflation?'Known inflation':'Construction'}</span><strong>${entry.inflation?`\\(${entry.n===5?'\\varphi=(1+\\sqrt5)/2':entry.inflation}\\)`:(entry.id==='p1'?'Finite reference':entry.id==='tri7'?'Root-lattice section':'Multigrid section')}</strong></div>`;
  $('sources').innerHTML=entry.links.map(k=>`<a href="${sources[k][1]}" target="_blank" rel="noreferrer">${sources[k][0]} ↗</a>`).join('')+(entry.search?`<a href="${entry.search[1]}">${entry.search[0]} →</a>`:'');
  const frozen=entry.id==='p1';$('radius').disabled=frozen;$('phase').disabled=frozen;$('animation').querySelector('[value="phase"]').disabled=frozen;
  $('arrows').disabled=entry.id!=='p3';$('overlay').disabled=!['p2','robinson'].includes(entry.id);
  if($('arrows').disabled)$('arrows').checked=false;if($('overlay').disabled)$('overlay').checked=false;
  if(frozen&&$('animation').value==='phase')$('animation').value='reveal';
  $('internalCaption').innerHTML=`\\(\\zeta_{${entry.n}}\\mapsto\\zeta_{${entry.n}}^{${entry.n%2?2:entry.n===12?5:3}}\\)${model.r.degree>4?'<br>One internal-plane projection.':'<br>Conjugate vertex coordinates.'}`;
  makeLegend();math([$('facts'),$('description'),$('relation'),$('internalCaption')]);
}
function makeLegend(){const types=new Map();for(const t of model.tiles)if(!types.has(t.kind))types.set(t.kind,t);$('legend').replaceChildren();
  for(const[k,t]of [...types].sort(([a],[b])=>a.localeCompare(b))){const b=document.createElement('button');b.dataset.kind=k;b.setAttribute('aria-pressed',String(filter===k));b.title='Highlight this shape';b.innerHTML=`<i class="swatch" style="background:${color(k)}"></i>${shapeName(t)}`;b.onclick=()=>{filter=filter===k?null:k;for(const e of $('legend').children)e.setAttribute('aria-pressed',String(e.dataset.kind===filter));dirty=true;};$('legend').append(b);}math([$('legend')]);
}
function choose(item){entry=item;selected=null;hover=null;filter=null;gained.clear();zoom=1;pan=[0,0];$('inspection').innerHTML='<p>Click a tile to see its shape and its exact cyclotomic address.</p>';
  for(const b of document.querySelectorAll('.tile-card'))b.setAttribute('aria-pressed',String(b.dataset.tiling===entry.id));
  const url=new URL(location.href);url.searchParams.set('tiling',entry.id);history.replaceState(null,'',url);
  construct(true);reveal=playing&&$('animation').value==='reveal'?0:1;$('reveal').value=String(Math.round(reveal*1000));updateTransport();
}
function construct(updateInfo=false){
  const start=performance.now();try{
    const next=buildAtlas(entry.id,{radius,phase});const audit=inspectPatch(next);
    if(audit.nonmanifold||audit.duplicates||audit.minArea<=0)throw Error('Patch geometry check failed');
    const oldIds=new Set(model?.tiles.map(t=>t.id)||[]);gained=new Set(next.tiles.filter(t=>!oldIds.has(t.id)).map(t=>t.id));
    model=next;model.phase=phase;arrows=null;generation++;if(selected&&!model.tiles.some(t=>t.id===selected.id)){selected=null;$('inspection').innerHTML='<p>The selected tile changed during section motion. Click another tile to inspect it.</p>';}
    $('method').textContent=`${model.construction} · ${(performance.now()-start).toFixed(0)} ms`;
    $('status').textContent=entry.id==='p1'?'Finite reference · reveal and inspect':'Constructed patch · integer vertex addresses';
    if(updateInfo)info();dirty=true;
  }catch(error){$('status').textContent=error.message+' Showing the last regular patch.';}
}
function updateTransport(){const count=Math.floor((model?.tiles.length||0)*reveal);$('reveal').value=String(Math.round(reveal*1000));$('count').value=`${count.toLocaleString()} / ${(model?.tiles.length||0).toLocaleString()} tiles`;$('play').textContent=playing?'Pause':'Play';$('empty').hidden=count>0;}
function resize(){const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);internal.width=270;internal.height=224;dirty=true;}
function path(context,t,transform){context.beginPath();t.points.forEach((p,i)=>{const q=transform(p);i?context.lineTo(...q):context.moveTo(...q);});context.closePath();}
function transform(p){return [width/2+pan[0]+scale*p[0],height/2+pan[1]-scale*p[1]];}
function visible(){return model.tiles.slice(0,Math.floor(model.tiles.length*reveal));}
function draw(){if(!model)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);scale=Math.min(width,height)/(2*(entry.id==='p1'?14:radius)+3)*zoom;
  const tiles=visible();
  for(const t of tiles){path(ctx,t,transform);ctx.globalAlpha=filter&&t.kind!==filter?0.13:1;ctx.fillStyle=color(t.kind);ctx.fill();ctx.strokeStyle='#3b594b';ctx.lineWidth=.6;ctx.stroke();
    if(playing&&$('animation').value==='phase'&&gained.has(t.id)){ctx.strokeStyle='#fff9d4';ctx.lineWidth=1.9;ctx.stroke();}}
  ctx.globalAlpha=1;
  if($('overlay').checked&&model.sourceTiles){ctx.strokeStyle='#fffbed';ctx.lineWidth=1.5;for(const t of model.sourceTiles){if(t.center[0]**2+t.center[1]**2>(radius*Math.sqrt(reveal))**2)continue;path(ctx,t,transform);ctx.stroke();}}
  if($('arrows').checked&&entry.id==='p3'){
    if(!arrows)arrows=penroseArrows(model);ctx.strokeStyle='#284436';ctx.lineWidth=.9;
    for(const t of tiles)for(const a of arrows.get(t.id)){const p=transform(t.points[a.from]),q=transform(t.points[a.to]),dx=q[0]-p[0],dy=q[1]-p[1],len=Math.hypot(dx,dy),ux=dx/len,uy=dy/len,size=Math.min(3.4,scale*.15);
      for(let h=0;h<a.type;h++){const shift=(h-(a.type-1)/2)*size*1.4,c=[(p[0]+q[0])/2+ux*shift,(p[1]+q[1])/2+uy*shift];ctx.beginPath();ctx.moveTo(c[0]-ux*size-uy*size*.7,c[1]-uy*size+ux*size*.7);ctx.lineTo(...c);ctx.lineTo(c[0]-ux*size+uy*size*.7,c[1]-uy*size-ux*size*.7);ctx.stroke();}}
  }
  for(const t of [hover,selected])if(t&&tiles.some(v=>v.id===t.id)){path(ctx,t,transform);ctx.strokeStyle=selected?.id===t.id?'#174b42':'#fdfbe9';ctx.lineWidth=2.7;ctx.stroke();}
  drawInternal(tiles);updateTransport();dirty=false;
}
function drawInternal(tiles){ic.setTransform(2,0,0,2,0,0);ic.clearRect(0,0,135,112);if($('internalBody').hidden)return;
  const power=entry.n%2?2:entry.n===12?5:3,all=new Map();for(const t of model.tiles)for(const c of t.coords)all.set(c.join(','),model.r.embed(c,power));
  const points=[...all.values()],max=Math.max(1,...points.flatMap(p=>p.map(Math.abs))),s=48/max,seen=new Set();
  ic.fillStyle='#789d8650';for(const p of points){ic.beginPath();ic.arc(67+p[0]*s,56-p[1]*s,.6,0,2*Math.PI);ic.fill();}
  ic.fillStyle='#276f60';for(const t of tiles)for(const c of t.coords){const key=c.join(',');if(seen.has(key))continue;seen.add(key);const p=all.get(key);ic.beginPath();ic.arc(67+p[0]*s,56-p[1]*s,.9,0,2*Math.PI);ic.fill();}
  if(selected){ic.strokeStyle='#bf7651';ic.lineWidth=1.2;ic.beginPath();selected.coords.forEach((c,i)=>{const p=model.r.embed(c,power);i?ic.lineTo(67+p[0]*s,56-p[1]*s):ic.moveTo(67+p[0]*s,56-p[1]*s);});ic.closePath();ic.stroke();}
}
function inside(point,polygon){let yes=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
function at(event){const r=canvas.getBoundingClientRect();return [(event.clientX-r.left-width/2-pan[0])/scale,-(event.clientY-r.top-height/2-pan[1])/scale];}
function hit(event){const p=at(event);return visible().find(t=>inside(p,t.points))||null;}
function inspect(tile){selected=tile;if(!tile){$('inspection').innerHTML='<p>Click a tile to see its shape and its exact cyclotomic address.</p>';return;}
  $('inspection').innerHTML=`<p><strong>${shapeName(tile)}</strong><br>${tile.points.length} vertices</p><p>First vertex in the integral basis:</p><p>\\(z=${polynomial(tile.coords[0],entry.n)}\\)</p><p>Coefficient vector:<br>\\((${tile.coords[0].join(',\\,')})\\)</p><p>All polygon vertices lie in \\(\\mathbb Z[\\zeta_{${entry.n}}]\\). The highlighted polygon in the inset uses the other embedding.</p>`;math([$('inspection')]);dirty=true;
}
canvas.addEventListener('pointerdown',event=>{canvas.setPointerCapture(event.pointerId);drag={x:event.clientX,y:event.clientY,pan:[...pan],moved:false};});
canvas.addEventListener('pointermove',event=>{if(drag){const dx=event.clientX-drag.x,dy=event.clientY-drag.y;drag.moved ||=Math.hypot(dx,dy)>4;pan=[drag.pan[0]+dx,drag.pan[1]+dy];}else hover=hit(event);dirty=true;});
canvas.addEventListener('pointerup',event=>{if(drag&&!drag.moved)inspect(hit(event));drag=null;});canvas.addEventListener('pointercancel',()=>{drag=null;});canvas.addEventListener('pointerleave',()=>{hover=null;dirty=true;});
canvas.addEventListener('wheel',event=>{event.preventDefault();const old=zoom;zoom=Math.max(.4,Math.min(6,zoom*Math.exp(-event.deltaY*.001)));const rect=canvas.getBoundingClientRect(),p=[event.clientX-rect.left-width/2,event.clientY-rect.top-height/2];pan=p.map((v,i)=>v-(v-pan[i])*zoom/old);dirty=true;},{passive:false});
canvas.addEventListener('keydown',event=>{if(event.key==='Escape'){inspect(null);dirty=true;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();pan[0]+=event.key==='ArrowLeft'?30:event.key==='ArrowRight'?-30:0;pan[1]+=event.key==='ArrowUp'?30:event.key==='ArrowDown'?-30:0;dirty=true;}});
$('zoomIn').onclick=()=>{zoom=Math.min(6,zoom*1.25);dirty=true;};$('zoomOut').onclick=()=>{zoom=Math.max(.4,zoom/1.25);dirty=true;};$('fit').onclick=()=>{zoom=1;pan=[0,0];dirty=true;};
$('play').onclick=()=>{playing=!playing;if(playing&&reveal>=1&&$('animation').value==='reveal')reveal=0;updateTransport();dirty=true;};
$('restart').onclick=()=>{reveal=0;$('animation').value='reveal';playing=true;updateTransport();dirty=true;};
$('reveal').oninput=()=>{reveal=Number($('reveal').value)/1000;playing=false;dirty=true;updateTransport();};
$('animation').onchange=()=>{if($('animation').value==='phase')reveal=1;updateTransport();dirty=true;};
$('phase').oninput=()=>{phase=Number($('phase').value)/1000;$('phaseValue').value=phase.toFixed(3);reveal=1;clearTimeout(buildTimer);buildTimer=setTimeout(()=>construct(),30);dirty=true;};
$('radius').oninput=()=>{radius=Number($('radius').value);$('radiusValue').value=radius;clearTimeout(buildTimer);buildTimer=setTimeout(()=>construct(),60);dirty=true;};
$('arrows').onchange=$('overlay').onchange=()=>{dirty=true;};
$('embeddingToggle').onclick=()=>{const hidden=!$('internalBody').hidden;$('internalBody').hidden=hidden;$('embeddingToggle').textContent=hidden?'Show':'Hide';$('embeddingToggle').setAttribute('aria-expanded',String(!hidden));dirty=true;};
$('download').onclick=()=>{
  const points=model.tiles.flatMap(t=>t.points),xs=points.map(p=>p[0]),ys=points.map(p=>-p[1]),minX=Math.min(...xs)-.5,minY=Math.min(...ys)-.5,w=Math.max(...xs)-minX+.5,h=Math.max(...ys)-minY+.5;
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${minX} ${minY} ${w} ${h}"><title>${entry.name.replaceAll('&','&amp;')}</title><desc>Known construction from GCTS live atlas. Phase ${model.phase}. ${model.construction}. Colors indicate tile shapes/classes, not matching rules. Floating-point section selection; integer cyclotomic vertex addresses.</desc><rect x="${minX}" y="${minY}" width="${w}" height="${h}" fill="#f9faf5"/>${model.tiles.map(t=>`<polygon points="${t.points.map(p=>`${p[0]},${-p[1]}`).join(' ')}" fill="${color(t.kind)}" stroke="#3b594b" stroke-width="0.025"/>`).join('')}</svg>`;
  const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'})),link=document.createElement('a');link.href=url;link.download=`${entry.id}-phase-${model.phase.toFixed(3)}.svg`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
};
let last=0;
function frame(now){const dt=last?Math.min(100,now-last):0;last=now;
  if(playing&&model){if($('animation').value==='reveal'){reveal=Math.min(1,reveal+dt/8000);$('reveal').value=String(Math.round(reveal*1000));if(reveal===1)playing=false;dirty=true;}
    else if(now-phaseTick>180){phaseTick=now;phase+=phaseDirection*.008;if(phase>=1||phase<=0){phase=Math.max(0,Math.min(1,phase));phaseDirection*=-1;}$('phase').value=String(Math.round(phase*1000));$('phaseValue').value=phase.toFixed(3);construct();}}
  if(dirty)draw();requestAnimationFrame(frame);
}
makeLibrary();construct(true);if(!playing)reveal=1;new ResizeObserver(resize).observe(canvas);resize();requestAnimationFrame(frame);
// Read-only diagnostics for reproducible browser checks and exported evidence.
window.atlasSnapshot=()=>({id:entry.id,phase,radius,generation,playing,reveal,tiles:model?.tiles.length,visible:Math.floor((model?.tiles.length||0)*reveal),kinds:[...new Set(model?.tiles.map(t=>t.kind))],audit:model&&inspectPatch(model),selected:selected?.kind,signature:model?.tiles.map(t=>t.id).join(';')});
